import type { IELTSTest } from "./types";

export const ieltsReading12: IELTSTest = {
  id: "ielts-reading-12",
  exam: "IELTS",
  title: "IELTS Academic Reading — Test 12",
  totalSeconds: 3600,
  passages: [
    // ── PASSAGE 1 ────────────────────────────────────────────────────────────
    {
      number: 1,
      title: "Ocean Currents and Climate Regulation",
      paragraphs: [
        {
          letter: "A",
          text: "The world's oceans are far more than vast bodies of water; they function as the planet's primary heat distribution system. Through a complex network of surface currents and deep-water circulation, the oceans absorb solar energy in the tropics and transport it toward the poles, moderating temperature extremes across vast regions of the Earth's surface. Without this thermoregulatory function, land masses at high latitudes would be substantially colder and those near the equator far hotter. Scientists estimate that the oceans absorb approximately 90 percent of the excess heat generated by anthropogenic greenhouse gas emissions, making ocean circulation central to any meaningful understanding of global climate dynamics.",
        },
        {
          letter: "B",
          text: "Surface currents are driven primarily by wind patterns and the Earth's rotation — a phenomenon known as the Coriolis effect. In the Northern Hemisphere, the Coriolis effect deflects moving water to the right, creating large circular current systems called gyres. The five major ocean gyres — the North and South Pacific, the North and South Atlantic, and the Indian Ocean gyres — each rotate in predictable patterns that govern the movement of nutrients, marine organisms, and floating debris across entire ocean basins. The Gulf Stream, one of the most studied surface currents, transports warm water northward along the eastern coast of North America before crossing the Atlantic toward Europe, delivering heat that keeps the British Isles and Scandinavia substantially warmer than their latitudes would otherwise allow.",
        },
        {
          letter: "C",
          text: "Below the surface, a slower and more profound system operates: the thermohaline circulation, often called the global ocean conveyor belt. This deep-water circulation is driven not by wind but by differences in water density, which are themselves determined by temperature and salinity. Cold, salty water is denser than warm, fresh water and therefore sinks; in key locations such as the North Atlantic and around Antarctica, surface water loses heat to the atmosphere, becomes denser, and descends to the ocean floor, where it travels slowly along the seabed for centuries before rising again in a process called upwelling. This vast circuit takes approximately 1,000 years to complete a full cycle and plays a critical role in regulating both ocean chemistry and atmospheric carbon concentrations.",
        },
        {
          letter: "D",
          text: "The thermohaline circulation also drives the delivery of oxygen and nutrients to deep ocean waters, sustaining ecosystems that would otherwise be effectively lifeless. Where upwelling brings cold, nutrient-rich water to the surface — particularly along the western coasts of continents — marine productivity soars. The Humboldt Current off the coast of Peru and Chile supports one of the most productive fisheries on Earth, sustaining populations of anchovies, sardines, and the numerous predators that depend on them. Disruptions to upwelling, such as those caused by El Niño events — periodic warming of the central and eastern Pacific Ocean — can devastate these ecosystems and have cascading effects on food security across multiple continents.",
        },
        {
          letter: "E",
          text: "Climate scientists have raised serious concerns about the stability of ocean circulation under conditions of accelerating global warming. The Atlantic Meridional Overturning Circulation (AMOC), of which the Gulf Stream forms a part, has been identified as a potential tipping point in the Earth's climate system. Evidence from ocean monitoring buoys and sediment cores indicates that AMOC has weakened by approximately 15 percent since the mid-twentieth century, likely due to increased freshwater input from melting Greenland ice sheets diluting the salty North Atlantic water that drives the system's descent. Some modelling studies suggest that a significant weakening or collapse of AMOC could trigger dramatic cooling across Europe, disruption of monsoon systems in Africa and Asia, and rising sea levels along the eastern coast of North America.",
        },
        {
          letter: "F",
          text: "Monitoring ocean circulation presents formidable technical challenges. The depths at which thermohaline circulation operates are largely inaccessible to conventional instruments, and the timescales involved dwarf those of any human observation programme. The Argo float network, established in the early 2000s, has substantially improved real-time data collection by deploying thousands of autonomous drifting instruments that descend to 2,000 metres, take measurements, and surface to transmit data via satellite. Complementary information is extracted from seafloor sediments, coral skeletons, and ice cores, which preserve chemical signatures that allow scientists to reconstruct ocean conditions over thousands of years. Nevertheless, significant gaps remain in scientists' ability to predict the pace and consequences of circulation changes.",
        },
        {
          letter: "G",
          text: "The relationship between ocean currents and atmospheric systems is bidirectional and deeply complex, meaning that changes in circulation can themselves alter the winds and precipitation patterns that partly drive surface currents. This feedback architecture makes ocean circulation one of the most uncertain components of global climate projections. International research programmes, including those coordinated by the World Climate Research Programme, are investing heavily in improved ocean models and expanded observational networks in an attempt to reduce these uncertainties. The stakes are considerable: the ocean's capacity to buffer climate change is finite, and understanding the limits of that buffer is one of the most urgent scientific questions of the twenty-first century.",
        },
      ],
      sections: [
        {
          type: "match_headings",
          questionRange: "Questions 1–6",
          instructions:
            "The reading passage has seven paragraphs, A–G. Choose the correct heading for paragraphs B–G from the list of headings below.",
          headings: [
            { label: "i",    text: "The role of oceans in distributing the planet's heat" },
            { label: "ii",   text: "Surface currents and the forces that generate them" },
            { label: "iii",  text: "The slow deep-water circulation and how it works" },
            { label: "iv",   text: "Ecological and food system benefits of upwelling" },
            { label: "v",    text: "Signs of weakening in a critical circulation system" },
            { label: "vi",   text: "The difficulties of measuring deep ocean processes" },
            { label: "vii",  text: "The complex feedback between oceans and the atmosphere" },
            { label: "viii", text: "Economic costs of disrupted ocean currents" },
            { label: "ix",   text: "Historical changes in oceanic salinity levels" },
          ],
          questions: [
            { id: 1, paragraph: "B", correct: "ii",   explanation: "Paragraph B describes wind-driven surface currents, the Coriolis effect, gyres, and the Gulf Stream." },
            { id: 2, paragraph: "C", correct: "iii",  explanation: "Paragraph C explains thermohaline circulation — driven by density differences in temperature and salinity — and the 1,000-year cycle." },
            { id: 3, paragraph: "D", correct: "iv",   explanation: "Paragraph D discusses how upwelling delivers nutrients to support marine ecosystems such as the Humboldt Current fisheries." },
            { id: 4, paragraph: "E", correct: "v",    explanation: "Paragraph E presents evidence that AMOC has weakened by 15 percent and discusses potential consequences of further collapse." },
            { id: 5, paragraph: "F", correct: "vi",   explanation: "Paragraph F addresses the technical challenges of monitoring deep circulation, including the Argo float network." },
            { id: 6, paragraph: "G", correct: "vii",  explanation: "Paragraph G explains the bidirectional feedback between ocean circulation and atmospheric systems and the resulting uncertainty in climate projections." },
          ],
        },
        {
          type: "tfng",
          questionRange: "Questions 7–10",
          instructions:
            "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE, or NOT GIVEN.",
          questions: [
            { id: 7,  statement: "The oceans absorb the majority of the extra heat produced by human greenhouse gas emissions.", correct: "True",      explanation: "Paragraph A explicitly states that 'the oceans absorb approximately 90 percent of the excess heat generated by anthropogenic greenhouse gas emissions.'" },
            { id: 8,  statement: "The thermohaline circulation completes a full cycle in approximately 100 years.", correct: "False",     explanation: "Paragraph C states the circuit takes 'approximately 1,000 years to complete a full cycle,' not 100 years." },
            { id: 9,  statement: "El Niño events are caused by changes in the thermohaline circulation.", correct: "Not Given", explanation: "The passage mentions El Niño as a disruption to upwelling but does not explain what causes El Niño events." },
            { id: 10, statement: "AMOC has measurably weakened since the middle of the twentieth century.", correct: "True",      explanation: "Paragraph E states that evidence indicates 'AMOC has weakened by approximately 15 percent since the mid-twentieth century.'" },
          ],
        },
        {
          type: "sentence_completion",
          questionRange: "Questions 11–13",
          instructions:
            "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
          questions: [
            { id: 11, before: "The circular current systems in the world's oceans, driven by wind and the Coriolis effect, are called ", after: ".", correct: "gyres", explanation: "Paragraph B: 'creating large circular current systems called gyres.'" },
            { id: 12, before: "The Argo float network deploys autonomous instruments that descend to ", after: " metres before surfacing to transmit data.", correct: "2,000", explanation: "Paragraph F: Argo floats 'descend to 2,000 metres, take measurements, and surface to transmit data via satellite.'" },
            { id: 13, before: "Information about past ocean conditions can be extracted from seafloor sediments, coral skeletons, and ", after: ", which preserve chemical signatures over thousands of years.", correct: "ice cores", explanation: "Paragraph F lists 'seafloor sediments, coral skeletons, and ice cores' as sources of historical ocean data." },
          ],
        },
      ],
    },

    // ── PASSAGE 2 ────────────────────────────────────────────────────────────
    {
      number: 2,
      title: "The Science of Human Aging",
      paragraphs: [
        {
          letter: "A",
          text: "Aging is one of biology's most universal yet poorly understood phenomena. At the cellular level, aging involves the progressive accumulation of molecular damage — to DNA, proteins, and lipid membranes — that eventually impairs normal function and increases vulnerability to disease. While all multicellular organisms age, the rate at which they do so varies enormously: a mayfly completes its adult life in a single day, while the Greenland shark has been estimated to live for more than 400 years. Understanding why aging rates differ so dramatically across species, and what determines the pace of aging within a given organism, has become one of the central questions of biogerontology — the scientific study of biological aging.",
        },
        {
          letter: "B",
          text: "Several competing theories have been proposed to explain the mechanisms of cellular aging. The telomere shortening hypothesis holds that each time a cell divides, the protective caps at the ends of chromosomes — called telomeres — become slightly shorter. Once telomeres reach a critical minimum length, the cell enters a state called replicative senescence, in which it can no longer divide and gradually begins to malfunction. A related but distinct concept is the free radical theory of aging, which attributes cellular damage to reactive oxygen species (ROS) — unstable molecules produced as a byproduct of normal metabolism that chemically attack DNA, proteins, and cellular membranes. Both theories have substantial experimental support, though neither fully explains all observed patterns of aging.",
        },
        {
          letter: "C",
          text: "Caloric restriction has emerged as one of the most robust interventions for extending lifespan in laboratory organisms. Studies in yeast, nematode worms, fruit flies, and rodents have consistently shown that reducing caloric intake by 20 to 40 percent — while maintaining adequate nutrition — significantly extends maximum lifespan. The mechanism appears to involve reduced production of reactive oxygen species, enhanced DNA repair activity, and activation of longevity-associated proteins called sirtuins. Whether caloric restriction exerts comparable effects in humans remains uncertain, and implementing such a regimen over a human lifetime presents obvious practical difficulties.",
        },
        {
          letter: "D",
          text: "Research into the genetics of exceptional human longevity has identified specific genomic variants associated with reaching 100 years of age or beyond. Studies of centenarian populations in regions such as Sardinia, Okinawa, and among the Seventh-day Adventist community in Loma Linda, California, have revealed that long-lived individuals tend to share not only certain genetic profiles but also particular lifestyle characteristics: plant-dominant diets, regular moderate physical activity, strong social ties, and clear sense of purpose. These findings have contributed to the concept of 'Blue Zones' — geographic areas with unusually high concentrations of centenarians — and have prompted debate about the relative contribution of genetics versus environment to exceptional longevity.",
        },
        {
          letter: "E",
          text: "The pharmaceutical pursuit of anti-aging interventions has accelerated dramatically in the past decade. Rapamycin, an immunosuppressant drug that inhibits the mTOR signalling pathway — a key regulator of cell growth and metabolism — has extended lifespan in mouse models even when administered in middle age. Senolytic drugs, which selectively eliminate senescent cells that accumulate in aging tissues and drive inflammation, have demonstrated promising results in animal studies and are entering human clinical trials. Metformin, a widely prescribed diabetes medication, has attracted interest after epidemiological studies suggested that diabetic patients taking it had lower rates of age-related diseases than expected, prompting the TAME (Targeting Aging with Metformin) trial — one of the first clinical trials designed to test a drug against aging itself as a condition.",
        },
        {
          letter: "F",
          text: "The prospect of significantly extending healthy human lifespan raises profound ethical, social, and economic questions. If anti-aging interventions become effective but expensive, access disparities could create a world in which the wealthy live substantially longer than the poor, dramatically amplifying existing social inequalities. Extended lifespans would strain pension systems, reshape labour markets, and create new demands on healthcare infrastructure. Some philosophers argue that death is not simply a misfortune to be overcome but a necessary feature of a meaningful human life — that mortality gives urgency and poignancy to experience in ways that would be lost in an indefinitely extended existence. Others counter that reducing suffering and premature death has always been a legitimate goal of medicine, and that the boundary between treating disease and extending health is inherently arbitrary.",
        },
      ],
      sections: [
        {
          type: "match_info",
          questionRange: "Questions 14–19",
          instructions:
            "The reading passage has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter A–F.",
          paragraphLetters: ["A", "B", "C", "D", "E", "F"],
          questions: [
            { id: 14, text: "A description of geographic communities where people live unusually long lives", correct: "D", explanation: "Paragraph D describes Sardinia, Okinawa, and Loma Linda — the 'Blue Zones' — as areas with unusually high concentrations of centenarians." },
            { id: 15, text: "An explanation of how protective structures on chromosomes shorten with each cell division", correct: "B", explanation: "Paragraph B describes telomere shortening with each cell division, leading to replicative senescence." },
            { id: 16, text: "Reference to a clinical trial specifically targeting the aging process as a condition", correct: "E", explanation: "Paragraph E mentions the TAME trial as 'one of the first clinical trials designed to test a drug against aging itself as a condition.'" },
            { id: 17, text: "A philosophical argument that a finite lifespan may be important for human experience", correct: "F", explanation: "Paragraph F: 'Some philosophers argue that death is not simply a misfortune to be overcome but a necessary feature of a meaningful human life.'" },
            { id: 18, text: "Evidence that dramatically different aging rates are observed across different species", correct: "A", explanation: "Paragraph A contrasts the mayfly (one day) and the Greenland shark (over 400 years) as examples of enormous variation in aging rates." },
            { id: 19, text: "A finding that reduced food intake activates proteins associated with longer life", correct: "C", explanation: "Paragraph C: caloric restriction leads to 'activation of longevity-associated proteins called sirtuins.'" },
          ],
        },
        {
          type: "mc_single",
          questionRange: "Questions 20–23",
          instructions: "Choose the correct letter, A, B, C, or D.",
          questions: [
            {
              id: 20,
              stem: "According to paragraph B, what happens when telomeres reach a critical minimum length?",
              options: [
                { label: "A", text: "The cell produces excess reactive oxygen species." },
                { label: "B", text: "The cell can no longer divide and begins to malfunction." },
                { label: "C", text: "The chromosome breaks down entirely." },
                { label: "D", text: "The cell immediately undergoes programmed death." },
              ],
              correct: "B",
              explanation: "Paragraph B: 'Once telomeres reach a critical minimum length, the cell enters a state called replicative senescence, in which it can no longer divide and gradually begins to malfunction.'"
            },
            {
              id: 21,
              stem: "What does the passage indicate about caloric restriction in humans?",
              options: [
                { label: "A", text: "It has been proven to extend human lifespan in clinical trials." },
                { label: "B", text: "It is ineffective in humans because metabolism differs from that of rodents." },
                { label: "C", text: "Its effects on human longevity remain unconfirmed and are difficult to study." },
                { label: "D", text: "It increases sirtuin production but reduces DNA repair activity." },
              ],
              correct: "C",
              explanation: "Paragraph C: 'Whether caloric restriction exerts comparable effects in humans remains uncertain, and implementing such a regimen over a human lifetime presents obvious practical difficulties.'"
            },
            {
              id: 22,
              stem: "What makes the TAME trial significant, according to the passage?",
              options: [
                { label: "A", text: "It is the first trial to test rapamycin in human subjects." },
                { label: "B", text: "It was prompted by the discovery of sirtuin proteins." },
                { label: "C", text: "It tests a drug specifically aimed at aging as a condition, not a single disease." },
                { label: "D", text: "It focuses exclusively on patients with type 2 diabetes." },
              ],
              correct: "C",
              explanation: "Paragraph E: the TAME trial is 'one of the first clinical trials designed to test a drug against aging itself as a condition.'"
            },
            {
              id: 23,
              stem: "Which concern about anti-aging treatments is raised in paragraph F?",
              options: [
                { label: "A", text: "Such treatments could cause unforeseen genetic mutations." },
                { label: "B", text: "Wealthier people may gain access to longer lives than poorer people." },
                { label: "C", text: "Governments will be unable to regulate the new pharmaceutical industry." },
                { label: "D", text: "Extended lifespans would reduce the quality of the aging experience." },
              ],
              correct: "B",
              explanation: "Paragraph F: 'access disparities could create a world in which the wealthy live substantially longer than the poor, dramatically amplifying existing social inequalities.'"
            },
          ],
        },
        {
          type: "summary_completion",
          questionRange: "Questions 24–26",
          instructions:
            "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
          summaryTitle: "Cellular Theories of Aging",
          summaryText:
            "Two prominent explanations for cellular aging are widely discussed by researchers. The first focuses on {{24}}, protective caps on chromosomes that become shorter each time a cell divides. When these structures become too short, the cell enters a state of replicative {{25}} and can no longer function normally. The second theory attributes damage to reactive oxygen species — unstable molecules that are produced as a byproduct of {{26}} and that attack DNA and other cellular structures.",
          wordBank: ["telomeres", "senescence", "metabolism", "division", "repair", "oxidation", "mitosis", "apoptosis"],
          questions: [
            { id: 24, blankId: 24, correct: "telomeres", explanation: "Paragraph B describes telomeres as the 'protective caps at the ends of chromosomes' that shorten with each cell division." },
            { id: 25, blankId: 25, correct: "senescence", explanation: "Paragraph B: when telomeres reach minimum length, 'the cell enters a state called replicative senescence.'" },
            { id: 26, blankId: 26, correct: "metabolism", explanation: "Paragraph B: reactive oxygen species are 'produced as a byproduct of normal metabolism.'" },
          ],
        },
      ],
    },

    // ── PASSAGE 3 ────────────────────────────────────────────────────────────
    {
      number: 3,
      title: "Smart Cities and Urban Technology",
      paragraphs: [
        {
          letter: "A",
          text: "The concept of the smart city has moved rapidly from academic speculation to practical policy in the first decades of the twenty-first century. Broadly defined, a smart city uses digital technology and data analytics to improve the efficiency of urban services, enhance quality of life for residents, and reduce environmental impact. Sensors embedded in infrastructure, real-time data platforms, artificial intelligence algorithms, and ubiquitous connectivity form the technical backbone of smart city systems. Cities as diverse as Singapore, Barcelona, Amsterdam, and Songdo in South Korea have invested heavily in smart city infrastructure, though the scale, ambition, and outcomes of these programmes vary considerably.",
        },
        {
          letter: "B",
          text: "Transportation management is one of the domains where smart city technologies have demonstrated the clearest gains. Adaptive traffic signal systems, which adjust signal timing in real time based on traffic sensor data, have been shown to reduce average journey times and lower vehicle emissions in pilot deployments across multiple cities. Integrated public transport apps that provide real-time arrival information, multimodal journey planning, and seamless digital ticketing have increased transit ridership in several European cities. In Singapore, the Land Transport Authority's Electronic Road Pricing system uses dynamic congestion pricing to manage vehicle density on key arterial roads, reducing both journey times and pollution in the central business district.",
        },
        {
          letter: "C",
          text: "Energy management represents another significant application domain. Smart electricity grids — which use two-way communication between utilities and consumers, advanced metering infrastructure, and machine learning algorithms to predict and balance supply and demand — can significantly reduce energy waste and facilitate the integration of intermittent renewable energy sources such as solar and wind power. In Amsterdam's smart grid pilot, residential customers who received real-time feedback on their electricity consumption reduced their energy use by an average of 14 percent. Smart building management systems, which automatically adjust heating, cooling, and lighting based on occupancy patterns and weather forecasts, offer complementary savings in the commercial sector.",
        },
        {
          letter: "D",
          text: "The proliferation of sensors and data platforms in urban environments raises fundamental questions about privacy and surveillance. Smart city systems routinely collect data on citizens' movements, behaviours, and interactions with urban infrastructure — data that is often aggregated and analysed without meaningful consent or transparency. The Smart City project developed by Google's sibling company Sidewalk Labs in Toronto's Quayside neighbourhood was abandoned in 2020 following sustained criticism from privacy advocates who argued that the company's data governance proposals were inadequate and that the project would effectively transform a public neighbourhood into a corporate data extraction operation. The episode highlighted the tension between the efficiency gains promised by smart city technologies and the civil liberties implications of pervasive urban monitoring.",
        },
        {
          letter: "E",
          text: "Critics have also challenged the assumption that smart city technologies benefit all urban residents equally. Research has consistently found that digital infrastructure investments tend to be concentrated in economically prosperous districts, while poorer neighbourhoods receive fewer sensors, less reliable connectivity, and more limited access to the services that data-driven platforms enable. This pattern of digital gentrification risks compounding existing urban inequalities: wealthier residents gain access to optimised transport, energy savings, and improved public services, while disadvantaged communities are doubly excluded — both from the benefits of the technology and from meaningful participation in decisions about its deployment.",
        },
        {
          letter: "F",
          text: "Despite these concerns, the trajectory of smart city development is unlikely to reverse. The declining cost of sensors, the expansion of 5G connectivity, and the increasing computational power of edge computing devices are making ubiquitous urban data collection progressively cheaper and more feasible. The challenge for urban policymakers, civil society organisations, and researchers is to develop governance frameworks that harness the genuine efficiency and sustainability benefits of smart city technologies while preventing the concentration of data power in the hands of a small number of technology corporations and ensuring that the benefits of digital urbanism are equitably distributed across all communities.",
        },
      ],
      sections: [
        {
          type: "ynng",
          questionRange: "Questions 27–31",
          instructions:
            "Do the following statements agree with the claims of the writer in the reading passage? Write YES, NO, or NOT GIVEN.",
          questions: [
            { id: 27, statement: "Smart city technologies have delivered clearer improvements in transportation than in most other domains.", correct: "Yes",       explanation: "Paragraph B: the writer states that transportation is 'one of the domains where smart city technologies have demonstrated the clearest gains.'" },
            { id: 28, statement: "Amsterdam residents who received real-time energy feedback reduced consumption by more than 20 percent.", correct: "No",        explanation: "Paragraph C states the reduction was 'an average of 14 percent,' not more than 20 percent." },
            { id: 29, statement: "The Sidewalk Labs Toronto project was cancelled primarily for financial reasons.", correct: "No",        explanation: "Paragraph D states the project was abandoned 'following sustained criticism from privacy advocates,' not for financial reasons." },
            { id: 30, statement: "Digital infrastructure in cities tends to be distributed unevenly in favour of wealthier areas.", correct: "Yes",       explanation: "Paragraph E: 'digital infrastructure investments tend to be concentrated in economically prosperous districts, while poorer neighbourhoods receive fewer sensors.'" },
            { id: 31, statement: "The writer believes the growth of smart city technology will eventually slow due to privacy concerns.", correct: "No",        explanation: "Paragraph F states the trajectory 'is unlikely to reverse,' citing declining sensor costs and expanding 5G connectivity." },
          ],
        },
        {
          type: "mc_multiple",
          questionRange: "Questions 32–34",
          instructions:
            "Choose TWO letters, A–E.",
          questions: [
            {
              id: 32,
              stem: "Which TWO smart city applications are described in the passage as having produced measurable benefits?",
              options: [
                { label: "A", text: "Adaptive traffic signal systems reducing journey times" },
                { label: "B", text: "Facial recognition reducing urban crime" },
                { label: "C", text: "Smart grid feedback reducing residential energy use" },
                { label: "D", text: "AI systems diagnosing diseases in city hospitals" },
                { label: "E", text: "Automated waste collection systems" },
              ],
              pickCount: 2,
              correct: ["A", "C"],
              explanation: "Paragraph B describes adaptive traffic signals reducing journey times (A). Paragraph C describes Amsterdam residents reducing energy use by 14 percent through smart grid feedback (C)."
            },
            {
              id: 33,
              stem: "Which TWO criticisms of smart city projects are explicitly made in the passage?",
              options: [
                { label: "A", text: "They are prohibitively expensive for most cities to implement." },
                { label: "B", text: "They collect citizen data without adequate consent or transparency." },
                { label: "C", text: "They concentrate benefits in wealthier neighbourhoods." },
                { label: "D", text: "They are technically unreliable in extreme weather conditions." },
                { label: "E", text: "They have failed to reduce carbon emissions in any tested city." },
              ],
              pickCount: 2,
              correct: ["B", "C"],
              explanation: "Paragraph D criticises data collection 'without meaningful consent or transparency' (B). Paragraph E describes how benefits are concentrated in 'economically prosperous districts' (C)."
            },
            {
              id: 34,
              stem: "Which TWO technological developments does the writer identify as driving the continued growth of smart city infrastructure?",
              options: [
                { label: "A", text: "Increasing affordability of sensor technology" },
                { label: "B", text: "Government mandates for data sharing" },
                { label: "C", text: "The rollout of 5G connectivity" },
                { label: "D", text: "Improvements in satellite imaging" },
                { label: "E", text: "Public demand for digital public services" },
              ],
              pickCount: 2,
              correct: ["A", "C"],
              explanation: "Paragraph F cites 'the declining cost of sensors' (A) and 'the expansion of 5G connectivity' (C) as key drivers of continued smart city development."
            },
          ],
        },
        {
          type: "short_answer",
          questionRange: "Questions 35–40",
          instructions:
            "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
          questions: [
            { id: 35, before: "What term does the passage use to describe the process by which technology investment benefits prosperous areas at the expense of poorer communities?", correct: "digital gentrification", explanation: "Paragraph E introduces the term 'digital gentrification' to describe the pattern of unequal technology investment." },
            { id: 36, before: "Which city uses dynamic congestion pricing to control vehicle numbers on major roads?", correct: "Singapore", explanation: "Paragraph B: 'In Singapore, the Land Transport Authority's Electronic Road Pricing system uses dynamic congestion pricing to manage vehicle density.'" },
            { id: 37, before: "What type of computing technology, mentioned in paragraph F, is making urban data collection cheaper?", correct: "edge computing", explanation: "Paragraph F: 'the increasing computational power of edge computing devices are making ubiquitous urban data collection progressively cheaper.'" },
            { id: 38, before: "In paragraph C, what kind of energy sources does the smart grid help to incorporate into the electricity supply?", correct: "renewable energy", explanation: "Paragraph C: smart grids 'facilitate the integration of intermittent renewable energy sources such as solar and wind power.'" },
            { id: 39, before: "What type of company developed the abandoned Toronto Quayside smart city project?", correct: "sibling company", explanation: "Paragraph D describes Sidewalk Labs as a 'sibling company' of Google." },
            { id: 40, before: "Beyond efficiency, what quality does the writer say should characterise the distribution of smart city benefits?", correct: "equitably distributed", explanation: "Paragraph F: 'ensuring that the benefits of digital urbanism are equitably distributed across all communities.'" },
          ],
        },
      ],
    },
  ],
};
