import type { WritingTest } from "./writing-types";

export const ieltsWriting9: WritingTest = {
  id: "ielts-writing-9",
  exam: "IELTS",
  title: "IELTS Academic Writing — Test 9",
  totalSeconds: 3600,
  tasks: [
    {
      id: 1,
      type: "ielts_task1",
      taskLabel: "Task 1 — Academic Writing",
      instructions:
        "The diagram below shows how solar panels generate and distribute electricity for household use. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
      timeSeconds: 1200,
      minWords: 150,
      prompt:
        "The process diagram below illustrates how solar panels convert sunlight into electricity and distribute it to homes. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      chartDescription: `Process diagram: How Solar Panels Generate and Distribute Electricity

The diagram shows a sequential process with the following stages:

Stage 1 — Sunlight absorption:
Solar panels (photovoltaic cells) mounted on the roof of a building absorb sunlight. The panels contain silicon cells that convert solar radiation directly into direct current (DC) electricity.

Stage 2 — Conversion (inverter):
The DC electricity produced by the solar panels is fed into an inverter device. The inverter converts the DC electricity into alternating current (AC) electricity, which is the standard form used by household appliances.

Stage 3 — Distribution to household:
The AC electricity from the inverter is distributed through the building's electrical system, powering lights, appliances, and other household devices directly.

Stage 4 — Battery storage (optional):
Excess electricity that is not immediately consumed can be directed to a battery storage unit, where it is stored for later use — for example, during the night or on cloudy days when solar generation is low.

Stage 5 — Grid connection (export/import):
Any surplus electricity not stored in the battery can be exported to the national electricity grid. Conversely, when the solar panels are not generating sufficient electricity (e.g. at night), the household can draw power from the grid.

Stage 6 — Metering:
A smart meter records both the electricity generated by the solar panels and the electricity imported from or exported to the grid, enabling billing and monitoring.

Overall: The process is cyclical and adaptive, with solar energy flowing from panels through an inverter to the home, with surplus managed through battery storage or grid exchange.`,
      chartData: {
        type: "process",
        title: "How Solar Panels Generate and Distribute Electricity",
        processText: "Stage 1 — Sunlight absorption: Solar panels (photovoltaic cells) mounted on the roof absorb sunlight and convert solar radiation into direct current (DC) electricity via silicon cells. Stage 2 — Conversion (inverter): The DC electricity is fed into an inverter, which converts it into alternating current (AC) electricity compatible with household appliances. Stage 3 — Distribution to household: AC electricity from the inverter is distributed through the building's electrical system, powering lights and appliances. Stage 4 — Battery storage (optional): Excess electricity not immediately consumed is directed to a battery storage unit for later use during low-generation periods (e.g. night or cloudy days). Stage 5 — Grid connection (export/import): Surplus electricity not stored in the battery can be exported to the national grid; conversely, the household can draw power from the grid when solar generation is insufficient. Stage 6 — Metering: A smart meter records electricity generated and electricity imported from or exported to the grid for billing and monitoring purposes.",
      },
      modelAnswer: `The diagram illustrates the process by which solar panels capture sunlight and convert it into usable electricity for domestic consumption, including the management of surplus energy.

Overall, the process follows a clear linear sequence from energy capture to household distribution, with two additional pathways for handling excess electricity — battery storage and grid export.

The process begins when photovoltaic cells mounted on the roof absorb solar radiation and convert it into direct current (DC) electricity. This DC electricity is then fed into an inverter, which transforms it into alternating current (AC) — the standard form compatible with household appliances. The AC electricity is subsequently distributed throughout the building to power lights and devices.

When the solar panels generate more electricity than the household requires, the surplus follows one of two routes. It may be directed to a battery storage unit, where it is held for use during periods of low generation, such as at night or on overcast days. Alternatively, excess power can be exported to the national grid. The reverse process also applies: when generation is insufficient, the household draws electricity from the grid. A smart meter records all flows — both generated and imported or exported — for monitoring and billing purposes.

In summary, the system is adaptive, balancing solar generation, household demand, storage, and grid interaction to ensure a reliable electricity supply.`,
      bandDescriptors: [
        {
          criterion: "Task Achievement",
          band7: "Describes the main stages of the process clearly; covers the key steps from solar absorption to household use and mentions surplus management; minor omissions do not significantly affect coverage.",
          band8: "Accurately and fully describes all stages of the process including the optional storage and grid pathways; the overview effectively captures the adaptive nature of the system.",
        },
        {
          criterion: "Coherence & Cohesion",
          band7: "Uses appropriate sequencing language (e.g. 'then', 'subsequently', 'when'); the process stages are presented in logical order.",
          band8: "Sequencing is seamless and varied; the branching pathways for surplus electricity are clearly distinguished and the overall process narrative flows naturally.",
        },
        {
          criterion: "Lexical Resource",
          band7: "Uses relevant technical vocabulary appropriately (e.g. 'photovoltaic', 'direct current', 'inverter'); some variation in descriptive language.",
          band8: "Employs precise technical and process language fluently (e.g. 'photovoltaic cells', 'alternating current', 'adaptive', 'overcast days'); vocabulary is accurate and varied throughout.",
        },
        {
          criterion: "Grammatical Range & Accuracy",
          band7: "Uses passive voice appropriately for process description; sentence structures are varied; minor errors do not impede understanding.",
          band8: "Passive constructions and complex sentences are used accurately and fluently; the response is grammatically varied and predominantly error-free.",
        },
      ],
    },
    {
      id: 2,
      type: "ielts_task2",
      taskLabel: "Task 2 — Academic Writing",
      instructions:
        "Write about the following topic. Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
      timeSeconds: 2400,
      minWords: 250,
      prompt:
        "Governments should spend more money on railways rather than building new roads. To what extent do you agree or disagree?",
      modelAnswer: `Transport infrastructure investment decisions have profound and lasting consequences for the environment, the economy, and the quality of urban life. The proposition that governments should prioritise railway development over new road construction is one I largely agree with, though I recognise that roads remain essential in certain contexts.

The arguments in favour of railway investment are compelling on both environmental and economic grounds. Rail transport produces significantly lower carbon emissions per passenger kilometre than private car travel, making it an essential component of any credible strategy to reduce greenhouse gas emissions in line with international climate commitments. High-speed rail networks in countries such as Japan, France, and China have demonstrated that investment in rail can reduce domestic air travel, ease road congestion, and connect regional economies in ways that stimulate long-term growth. Furthermore, railways are capacity-efficient: a single rail line can transport many times more passengers than an equivalent road lane, making them more effective in densely populated urban and inter-urban corridors.

By contrast, there are legitimate reasons why road investment may remain a priority in certain circumstances. In rural or remote regions where population density is low, building railways is rarely cost-effective, and roads are the primary means of connecting communities to essential services and markets. In many developing countries, expanding and maintaining basic road networks is a prerequisite for economic development.

However, in the majority of urban and inter-urban contexts that face growing congestion and pollution, continued road expansion often induces additional traffic rather than solving the underlying mobility problem — a phenomenon well-documented in transport research. In these settings, resources are more effectively directed toward rail.

In conclusion, while the optimal investment mix depends on geography and development context, the balance of evidence supports prioritising rail over new road construction in most cases, given the environmental and capacity advantages that modern rail systems offer.`,
      bandDescriptors: [
        {
          criterion: "Task Response",
          band7: "States a clear position in favour of railways with relevant supporting arguments; acknowledges the role of roads in rural contexts; ideas are generally well-developed.",
          band8: "Presents a well-nuanced position with a strong main argument supported by specific examples (Japan, France, China); the counterargument about rural roads is acknowledged and addressed; reasoning is thorough.",
        },
        {
          criterion: "Coherence & Cohesion",
          band7: "Essay is logically organised with a clear introduction, body paragraphs, and conclusion; transitions between paragraphs are appropriate.",
          band8: "Logical progression is maintained throughout; the acknowledgement of the counterargument is smoothly integrated and does not disrupt the overall argument; cohesion is natural.",
        },
        {
          criterion: "Lexical Resource",
          band7: "Uses relevant transport and policy vocabulary (e.g. 'greenhouse gas emissions', 'congestion', 'inter-urban'); lexical range is sufficient.",
          band8: "Employs precise and sophisticated vocabulary (e.g. 'induces additional traffic', 'capacity-efficient', 'credible strategy'); collocations are accurate and lexical variation is strong.",
        },
        {
          criterion: "Grammatical Range & Accuracy",
          band7: "Uses a variety of sentence structures; errors are infrequent and do not affect meaning.",
          band8: "Wide grammatical range including complex nominalisations, passive constructions, and subordinate clauses; the response is consistently accurate and fluent.",
        },
      ],
    },
  ],
};
