import type { PTETest } from "./types";

export const pteReading18: PTETest = {
  id: "pte-reading-18",
  exam: "PTE",
  title: "PTE Academic Reading — Test 18",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "Dark matter and dark energy are among the most profound mysteries in contemporary physics. Ordinary matter — the atoms, molecules, and particles that compose everything we can see, touch, or detect with conventional instruments — accounts for only approximately 5 percent of the total energy content of the universe. Dark matter, which interacts gravitationally but does not emit, absorb, or reflect light, is estimated to constitute around 27 percent. Its existence is inferred from observations of galaxy rotation curves, which show that galaxies rotate as if they contain far more mass than their visible components account for, and from gravitational lensing — the bending of light from distant objects by massive foreground structures. Dark energy, the remaining 68 percent, is even more enigmatic: it is invoked to explain the observed accelerating expansion of the universe, first detected in 1998 through observations of distant Type Ia supernovae. Neither dark matter nor dark energy has been directly detected; they are inferred from their gravitational effects on observable matter and light.",
      stem: "How was the accelerating expansion of the universe first detected?",
      options: [
        { label: "A", text: "Through observations of galaxy rotation curves." },
        { label: "B", text: "By measuring gravitational lensing effects." },
        { label: "C", text: "Through observations of distant Type Ia supernovae." },
        { label: "D", text: "By detecting dark matter particles in laboratory experiments." },
      ],
      correct: "C",
      explanation: "The passage states the accelerating expansion was 'first detected in 1998 through observations of distant Type Ia supernovae.'",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "Global food systems face a profound sustainability challenge: feeding a projected world population of nearly 10 billion people by 2050 while simultaneously reducing agriculture's enormous environmental footprint. Agriculture currently accounts for approximately 70 percent of freshwater withdrawals globally, occupies around 50 percent of habitable land, and is responsible for roughly 25 percent of global greenhouse gas emissions — including methane from livestock, nitrous oxide from fertilised soils, and carbon dioxide from deforestation. The transition to more sustainable food systems requires action across multiple dimensions: reducing food waste, shifting dietary patterns toward lower-impact foods, improving agricultural efficiency, restoring degraded farmland, and protecting remaining natural ecosystems from conversion. Alternative proteins — including plant-based meat substitutes, cultivated meat grown from animal cells, and insect protein — are attracting significant investment as potentially lower-impact sources of dietary protein. Critics note, however, that the environmental credentials of novel foods depend heavily on production methods and energy sources, and that the focus on food technology risks distracting from simpler dietary shifts that could be achieved without it.",
      stem: "Which TWO environmental impacts of agriculture are described in the passage?",
      options: [
        { label: "A", text: "It consumes the majority of the world's freshwater withdrawals." },
        { label: "B", text: "It is the leading cause of ocean acidification." },
        { label: "C", text: "It occupies approximately half of all habitable land." },
        { label: "D", text: "It produces the majority of global plastic waste." },
        { label: "E", text: "It is responsible for more greenhouse gas emissions than transport." },
      ],
      pickCount: 2,
      correct: ["A", "C"],
      explanation: "The passage states agriculture accounts for 'approximately 70 percent of freshwater withdrawals globally' (A) and 'occupies around 50 percent of habitable land' (C).",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "Democratic governance — the system in which political authority derives from the consent of the governed, expressed through free and fair elections — has its conceptual origins in ancient Athens, where male citizens participated directly in legislative assemblies." },
        { id: "s2", text: "The Athenian model was not sustained, and it was not until the seventeenth and eighteenth centuries that modern democratic theory was articulated by philosophers including John Locke, Jean-Jacques Rousseau, and the architects of the American and French Revolutions." },
        { id: "s3", text: "Representative democracy — in which citizens elect representatives to govern on their behalf — became the dominant model, addressing the practical impossibility of direct participation in large and complex modern states." },
        { id: "s4", text: "The twentieth century saw both the dramatic expansion of democratic governance worldwide and its violent repression under fascist and communist regimes, culminating in what Samuel Huntington termed the 'third wave of democratisation' from the 1970s onward." },
        { id: "s5", text: "Contemporary democratic systems face new challenges from within: declining voter participation, the rise of populist movements that claim democratic legitimacy while eroding institutional checks, and the manipulation of information environments by both domestic and foreign actors." },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation: "The sequence traces democracy chronologically: ancient Athens (s1) → Enlightenment theory and revolutions (s2) → representative model (s3) → twentieth century expansion and repression (s4) → contemporary challenges (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "Organic chemistry is the study of carbon-containing {{1}}, which form the molecular basis of all living organisms. Carbon is uniquely suited to this role because of its ability to form four stable {{2}} bonds simultaneously, enabling the construction of long chains, rings, and complex three-dimensional structures. Functional groups — specific arrangements of atoms within a molecule — determine a compound's chemical {{3}} and reactivity. For example, the hydroxyl group (-OH) characterises alcohols, while the carboxyl group (-COOH) is the defining feature of {{4}} acids. Pharmaceutical development relies heavily on organic chemistry to design molecules that interact with specific biological {{5}} and produce therapeutic effects with minimal side effects.",
      wordBank: ["compounds", "covalent", "properties", "carboxylic", "targets", "ionic", "reactions", "aromatic"],
      blanks: [
        { id: 1, correct: "compounds", explanation: "Organic chemistry studies carbon-containing 'compounds' — molecules based on carbon." },
        { id: 2, correct: "covalent", explanation: "Carbon forms four 'covalent bonds' — shared electron bonds — simultaneously." },
        { id: 3, correct: "properties", explanation: "Functional groups determine a compound's chemical 'properties' and reactivity." },
        { id: 4, correct: "carboxylic", explanation: "The -COOH group defines 'carboxylic acids' — the standard chemical term." },
        { id: 5, correct: "targets", explanation: "Pharmaceuticals interact with specific biological 'targets' — receptors, enzymes, etc." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "Public health interventions aim to {{1}} disease and injury at the population level, rather than treating individuals after illness occurs. The most cost-effective interventions are typically those that address the {{2}} determinants of health — factors such as poverty, education, housing quality, and access to nutritious food — rather than narrowly medical factors. Vaccination programmes represent perhaps the clearest example of successful public health action: by building {{3}} immunity within a population, vaccines protect even those who cannot be vaccinated, such as immunocompromised individuals. Non-communicable diseases — including cardiovascular disease, cancer, and diabetes — now account for the {{4}} of global mortality, and their prevention requires sustained action on behavioural risk factors including tobacco use, physical {{5}}, unhealthy diet, and harmful use of alcohol. Health systems that invest adequately in {{6}} care consistently achieve better population health outcomes than those that focus predominantly on curative hospital services.",
      rwfibBlanks: [
        { id: 1, options: ["prevent", "treat", "monitor", "study"], correct: "prevent", explanation: "Public health aims to 'prevent' disease — stop it before it occurs, at population level." },
        { id: 2, options: ["social", "genetic", "environmental", "biological"], correct: "social", explanation: "'Social determinants of health' is the established public health term for societal factors affecting health." },
        { id: 3, options: ["herd", "individual", "passive", "acquired"], correct: "herd", explanation: "'Herd immunity' — population-level protection through sufficient vaccination coverage — is the standard term." },
        { id: 4, options: ["majority", "minority", "entirety", "portion"], correct: "majority", explanation: "Non-communicable diseases account for the 'majority of global mortality' — most deaths worldwide." },
        { id: 5, options: ["inactivity", "activity", "labour", "exertion"], correct: "inactivity", explanation: "Physical 'inactivity' is a major risk factor for non-communicable diseases — lack of exercise." },
        { id: 6, options: ["primary", "secondary", "emergency", "specialist"], correct: "primary", explanation: "'Primary care' — first-contact, community-based healthcare — investment leads to better health outcomes." },
      ],
    },
  ],
};
