import type { PTETest } from "./types";

export const pteReading20: PTETest = {
  id: "pte-reading-20",
  exam: "PTE",
  title: "PTE Academic Reading — Test 20",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "Robotics is undergoing a period of rapid transformation driven by advances in artificial intelligence, sensor technology, and materials science. For most of the twentieth century, industrial robots were large, rigid, and confined to structured factory environments where they performed repetitive tasks with precision but without flexibility or adaptability. Contemporary robots — particularly collaborative robots, known as cobots — are designed to work alongside humans, with force-sensing capabilities that allow them to detect unexpected contact and stop safely. Soft robotics, which uses flexible, compliant materials inspired by biological organisms, is expanding the applications of robots into environments requiring delicate manipulation — including surgical assistance, food handling, and prosthetics. Advances in machine learning have enabled robots to learn tasks from demonstration rather than explicit programming, dramatically reducing the expertise required to deploy them. Despite this progress, robots remain far better at structured, repetitive physical tasks than at the unstructured, contextually complex manipulation and interaction that humans perform effortlessly.",
      stem: "What distinguishes contemporary cobots from traditional industrial robots?",
      options: [
        { label: "A", text: "They are exclusively used in surgical and medical settings." },
        { label: "B", text: "They can detect unexpected contact and stop safely to work alongside humans." },
        { label: "C", text: "They operate entirely without human supervision." },
        { label: "D", text: "They are programmed using natural language rather than code." },
      ],
      correct: "B",
      explanation: "The passage states cobots 'are designed to work alongside humans, with force-sensing capabilities that allow them to detect unexpected contact and stop safely.'",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "Ocean acidification — the ongoing reduction in the pH of Earth's oceans caused by the absorption of atmospheric carbon dioxide — represents a fundamental and largely irreversible change to marine chemistry. Since the Industrial Revolution, ocean pH has fallen from approximately 8.2 to 8.1, representing a 26 percent increase in acidity (because pH is a logarithmic scale). This seemingly modest chemical change has significant biological consequences: carbonate ion availability decreases as pH falls, impairing the ability of calcifying organisms — including corals, molluscs, echinoderms, and some phytoplankton — to build and maintain their calcium carbonate shells and skeletons. At projected CO₂ concentrations under high-emission scenarios, aragonite — the form of calcium carbonate used by corals — may become thermodynamically unstable in parts of the polar oceans by mid-century, meaning that existing coral structures would begin to dissolve. Pteropods — tiny free-swimming molluscs that form the base of many polar food webs — are already showing shell dissolution in naturally acidified upwelling zones, providing a preview of broader impacts. Ocean acidification does not affect all marine species negatively: some seagrasses and algae that use dissolved CO₂ for photosynthesis may benefit. However, the net effect on marine ecosystems is expected to be profoundly destabilising.",
      stem: "Which TWO biological consequences of ocean acidification are described in the passage?",
      options: [
        { label: "A", text: "Increased growth rates in all species of marine fish" },
        { label: "B", text: "Impaired ability of corals and molluscs to build their shells and skeletons" },
        { label: "C", text: "Shell dissolution in pteropods in acidified upwelling zones" },
        { label: "D", text: "Complete extinction of phytoplankton populations" },
        { label: "E", text: "Reduced oxygen levels in deep ocean water" },
      ],
      pickCount: 2,
      correct: ["B", "C"],
      explanation: "The passage describes reduced ability to build shells in calcifying organisms including corals (B) and shell dissolution already occurring in pteropods in acidified zones (C).",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "The concept of biodiversity — the variety of life on Earth at the genetic, species, and ecosystem levels — encompasses not only the number of species in a given area but the complexity of relationships between them and the range of ecological functions they perform." },
        { id: "s2", text: "Scientists estimate that approximately 8.7 million species exist on Earth, of which fewer than 2 million have been formally described and named, meaning the majority of life on our planet remains unknown to science." },
        { id: "s3", text: "The current rate of species extinction is estimated to be 100–1,000 times higher than background extinction rates inferred from the fossil record, leading scientists to describe our era as the sixth mass extinction event in Earth's history." },
        { id: "s4", text: "The primary drivers of this accelerating biodiversity loss include habitat destruction and fragmentation, overexploitation, invasive species, pollution, and climate change — all consequences of expanding human activity." },
        { id: "s5", text: "International frameworks including the Kunming-Montreal Global Biodiversity Framework, adopted in 2022, set targets to protect 30 percent of the planet's land and oceans by 2030, though translating these commitments into effective conservation action remains a significant governance challenge." },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation: "The sequence moves from defining biodiversity (s1) → the scale of undescribed species (s2) → the extinction crisis (s3) → its drivers (s4) → international policy responses (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "Ancient Rome's political system underwent several {{1}} transformations over its roughly thousand-year history. The early Roman Republic was governed by two elected {{2}} who held executive power for one year, supported by the Senate — a body of senior citizens that controlled finances and foreign policy. The Republic's constitution incorporated checks and balances designed to prevent any individual accumulating excessive power, though these {{3}} ultimately proved insufficient as military commanders acquired personal armies loyal to them rather than to the state. Julius Caesar's crossing of the Rubicon in 49 BCE triggered a civil war that ended the Republic, and his great-nephew Octavian — who took the title Augustus — established the Principate, a form of monarchy that maintained the {{4}} of republican institutions while concentrating real power in the emperor's hands. At its peak under the Five Good Emperors, the Roman Empire extended from Britain to Mesopotamia, but internal instability, {{5}} pressure on its borders, and economic strain eventually led to the decline and fall of the Western Empire in 476 CE.",
      wordBank: ["constitutional", "consuls", "safeguards", "facade", "military", "senatorial", "fiscal", "democratic"],
      blanks: [
        { id: 1, correct: "constitutional", explanation: "Rome's political system underwent 'constitutional transformations' — changes to its governing structure and laws." },
        { id: 2, correct: "consuls", explanation: "The Republic was governed by two elected 'consuls' — the senior magistrates of the Roman Republic." },
        { id: 3, correct: "safeguards", explanation: "The checks and balances were designed as 'safeguards' against excessive power — protective mechanisms." },
        { id: 4, correct: "facade", explanation: "Augustus maintained the 'facade of republican institutions' — the outward appearance without real power." },
        { id: 5, correct: "military", explanation: "The Empire declined partly due to 'military pressure on its borders' — external threats from barbarian groups." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "Cryptocurrency — digital currency that uses {{1}} techniques to secure transactions and control the creation of new units — emerged with the publication of the Bitcoin white paper by the pseudonymous Satoshi Nakamoto in 2008. Unlike conventional currencies issued by central banks, cryptocurrencies operate on {{2}} networks where no single authority controls the ledger of transactions. Bitcoin's underlying technology — the blockchain — is a {{3}} ledger in which transactions are grouped into blocks, cryptographically linked in sequence, and verified by a network of participants through a computationally intensive process called proof-of-work. This design makes the transaction history extremely resistant to {{4}}, as altering any record would require redoing all subsequent computational work. The dramatic price {{5}} of cryptocurrencies — Bitcoin rose from under US$1,000 in 2017 to nearly US$70,000 in 2021 before falling sharply — has led to their widespread use as speculative investments rather than as everyday mediums of {{6}}. Regulatory responses have ranged from outright prohibition in some countries to the development of central bank digital currencies (CBDCs) that aim to capture the efficiency benefits of digital payment while maintaining {{7}} control over monetary policy.",
      rwfibBlanks: [
        { id: 1, options: ["cryptographic", "biometric", "algorithmic", "numeric"], correct: "cryptographic", explanation: "Cryptocurrency uses 'cryptographic techniques' — methods based on mathematical encryption — to secure transactions." },
        { id: 2, options: ["decentralised", "centralised", "privatised", "regulated"], correct: "decentralised", explanation: "Cryptocurrencies operate on 'decentralised networks' — distributed systems with no single controlling authority." },
        { id: 3, options: ["distributed", "private", "encrypted", "centralised"], correct: "distributed", explanation: "The blockchain is a 'distributed ledger' — shared across many participants rather than held by one entity." },
        { id: 4, options: ["tampering", "copying", "expansion", "verification"], correct: "tampering", explanation: "Blockchain's design makes it resistant to 'tampering' — unauthorised alteration of transaction records." },
        { id: 5, options: ["volatility", "stability", "growth", "decline"], correct: "volatility", explanation: "The dramatic price 'volatility' — extreme swings up and down — describes Bitcoin's price behaviour." },
        { id: 6, options: ["exchange", "account", "investment", "storage"], correct: "exchange", explanation: "Money serves as a 'medium of exchange' — the standard economic term for currency used in transactions." },
        { id: 7, options: ["government", "market", "corporate", "international"], correct: "government", explanation: "CBDCs maintain 'government control' over monetary policy — central authority over the money supply." },
      ],
    },
  ],
};
