import type { PTETest } from "./types";

export const pteReading25: PTETest = {
  id: "pte-reading-25",
  exam: "PTE",
  title: "PTE Academic Reading — Test 25",
  totalSeconds: 1800,
  tasks: [
    // Task 1: Multiple Choice Single Answer — Genetic Engineering Ethics
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions:
        "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage:
        "The development of CRISPR-Cas9 gene-editing technology has transformed the ethical landscape of genetic engineering by making precise modifications to DNA sequences faster, cheaper, and more accessible than any previous technique. Originally identified as a bacterial immune defence mechanism, CRISPR has been adapted to edit the genomes of virtually any living organism, raising both extraordinary therapeutic possibilities and profound ethical concerns. In medicine, CRISPR holds genuine promise for correcting the genetic mutations responsible for hereditary conditions such as sickle-cell disease, cystic fibrosis, and Huntington's disease. Clinical trials using somatic gene editing — modifications that affect only the treated individual and are not heritable — have already produced encouraging results. The deeper controversy surrounds germline editing: modifications to eggs, sperm, or embryos that would be inherited by all subsequent generations. The 2018 announcement by Chinese researcher He Jiankui that he had created the world's first gene-edited babies shocked the scientific community and was widely condemned as premature and ethically unjustifiable, given the insufficiency of safety data and the absence of medical necessity. Beyond therapeutic applications, the possibility of using genetic engineering to enhance non-medical traits such as intelligence, physical appearance, or athletic ability — so-called 'designer babies' — raises the spectre of genetic inequality, with enhanced traits potentially accessible only to affluent families.",
      stem: "According to the passage, why was He Jiankui's announcement of gene-edited babies condemned by the scientific community?",
      options: [
        { label: "A", text: "The babies were edited for non-medical enhancements such as increased intelligence." },
        { label: "B", text: "The procedure was performed without adequate safety evidence and lacked medical justification." },
        { label: "C", text: "Germline editing had been explicitly banned by international treaty at the time of the announcement." },
        { label: "D", text: "He Jiankui had used an outdated gene-editing technique instead of CRISPR-Cas9." },
      ],
      correct: "B",
      explanation:
        "The passage states the work was 'widely condemned as premature and ethically unjustifiable, given the insufficiency of safety data and the absence of medical necessity' — directly supporting Option B. Option A is not mentioned in relation to He Jiankui's work. Option C is not stated — the passage mentions ethical concerns but not an international treaty ban. Option D is contradicted by the passage's context, which presents CRISPR as the current technique.",
    },

    // Task 2: Multiple Choice Multiple Answers — Smart Cities Infrastructure
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions:
        "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage:
        "Smart cities — urban environments that integrate digital technologies, sensor networks, and data analytics to improve the efficiency of services and enhance residents' quality of life — have moved from a conceptual vision to a practical reality in dozens of cities worldwide. At the infrastructure level, smart city systems encompass intelligent traffic management, adaptive street lighting, predictive maintenance of public utilities, real-time monitoring of air and water quality, and waste management systems that optimise collection routes based on sensor data from bins. The data generated by these interconnected systems is analysed using artificial intelligence and machine learning algorithms to identify patterns, predict failures, and allocate resources dynamically. Singapore, Barcelona, and Amsterdam are frequently cited as leading smart city implementations, having achieved measurable improvements in energy consumption, traffic congestion, and municipal service efficiency. However, the smart city model has attracted substantial criticism on grounds that extend beyond technical challenges. The collection of vast quantities of data about residents' movements, behaviours, and daily routines by both government bodies and private technology vendors raises serious questions about surveillance, consent, and data sovereignty. Critics point to the risk of 'smart' infrastructure deepening existing social inequalities if the benefits of digitally optimised services are concentrated in affluent districts while underserved communities receive little improvement. Cybersecurity vulnerabilities in interconnected urban systems also represent a significant risk: a successful attack on smart city infrastructure could simultaneously disrupt transport, utilities, emergency services, and communications.",
      stem: "According to the passage, which TWO concerns have critics raised about the smart city model?",
      options: [
        { label: "A", text: "The high financial cost of smart city technology, which may burden municipal budgets." },
        { label: "B", text: "The risk that digital benefits may be unevenly distributed, widening existing social inequalities." },
        { label: "C", text: "Surveillance and privacy risks arising from large-scale data collection about residents." },
        { label: "D", text: "The tendency of smart city AI systems to make biased decisions in criminal justice applications." },
        { label: "E", text: "The possibility that smart city systems will replace human workers in public service roles." },
      ],
      pickCount: 2,
      correct: ["B", "C"],
      explanation:
        "Option B is supported by the passage's warning that benefits 'concentrated in affluent districts while underserved communities receive little improvement' could deepen 'existing social inequalities.' Option C is directly supported by the concern about 'surveillance, consent, and data sovereignty' arising from vast data collection. Options A, D, and E are not mentioned in the passage.",
    },

    // Task 3: Re-order Paragraphs — History of Antibiotics
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions:
        "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        {
          id: "s1",
          text: "The discovery of antibiotics in the twentieth century is widely regarded as one of the greatest achievements in the history of medicine, transforming bacterial infections from leading causes of death into routinely treatable conditions.",
        },
        {
          id: "s2",
          text: "The story begins with Alexander Fleming's serendipitous observation in 1928 that a mould of the genus Penicillium had contaminated a bacterial culture and was inhibiting the growth of surrounding Staphylococcus colonies.",
        },
        {
          id: "s3",
          text: "Although Fleming recognised the potential significance of this finding, the challenge of isolating and purifying penicillin in sufficient quantities for therapeutic use was not overcome until Howard Florey and Ernst Chain developed extraction methods at Oxford in the early 1940s, enabling the drug's mass production in time to treat Allied wounded during World War II.",
        },
        {
          id: "s4",
          text: "The subsequent decades witnessed an extraordinary proliferation of antibiotic classes, with pharmaceutical companies discovering new compounds from soil bacteria, fungi, and synthetic chemistry, creating what appeared to be an inexhaustible arsenal against infection.",
        },
        {
          id: "s5",
          text: "Today, however, the spread of antimicrobial resistance — driven by the overuse and misuse of antibiotics in human medicine, veterinary practice, and agriculture — threatens to return humanity to the pre-antibiotic era, making infections caused by resistant organisms among the most urgent public health challenges of the twenty-first century.",
        },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation:
        "The passage follows a clear narrative arc: s1 establishes the historical importance of antibiotics; s2 identifies Fleming's 1928 discovery as the starting point; s3 explains how the clinical potential was realised by Florey and Chain in the 1940s; s4 describes the subsequent golden age of antibiotic discovery; s5 provides the contemporary challenge of antimicrobial resistance, completing the story from triumph to crisis.",
    },

    // Task 4: Reading Fill in the Blanks — Food Security and Population
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions:
        "In the text below, some words are missing. Click a word from the box, then click the blank where you want to place it. Each word may only be used once.",
      rfibText:
        "Food security — defined by the United Nations as the condition in which all people, at all times, have physical, social, and economic {{1}} to sufficient, safe, and nutritious food that meets their dietary needs for an active and healthy life — remains one of the most complex and politically charged global challenges. Despite the fact that global agricultural production currently generates enough calories to feed the entire world's population, an estimated 700 million people suffer from chronic hunger, revealing that food insecurity is primarily a problem of {{2}} and access rather than absolute scarcity of production. The world's population is projected to reach approximately 9.7 billion by 2050, placing enormous additional {{3}} on agricultural systems already strained by climate change, water scarcity, land degradation, and biodiversity loss. Meeting this future demand will require not only increasing food production but also dramatically reducing the approximately one-third of all food produced globally that is lost or {{4}} before it reaches a consumer. Dietary shifts in rapidly developing economies, where growing middle classes are adopting more meat-intensive diets, further complicate the equation: producing one kilogram of beef requires roughly fifteen times more water and generates several times more greenhouse gas emissions than producing an equivalent {{5}} of plant-based food.",
      wordBank: [
        "access",
        "distribution",
        "pressure",
        "wasted",
        "quantity",
        "demand",
        "spoiled",
        "weight",
      ],
      blanks: [
        {
          id: 1,
          correct: "access",
          explanation:
            "The UN definition of food security explicitly uses 'physical, social, and economic access to sufficient food.' 'Access' is the direct term used in this internationally recognised definition.",
        },
        {
          id: 2,
          correct: "distribution",
          explanation:
            "'A problem of distribution and access' — the passage has just stated that enough calories are produced globally, so the problem is not production but how food is distributed. 'Distribution' refers to the geographic and economic allocation of available food.",
        },
        {
          id: 3,
          correct: "pressure",
          explanation:
            "'Placing enormous additional pressure on agricultural systems' — 'pressure' is the standard collocation when population or demand exerts strain on systems or resources. 'Demand' would require a different preposition and sentence structure.",
        },
        {
          id: 4,
          correct: "wasted",
          explanation:
            "'Lost or wasted before it reaches a consumer' — 'food loss and waste' is the technical terminology used in food security discourse, where 'loss' occurs at production/storage stages and 'waste' occurs at retail/consumer stages. 'Spoiled' is a subset of waste but not the standard paired term with 'lost.'",
        },
        {
          id: 5,
          correct: "quantity",
          explanation:
            "'An equivalent quantity of plant-based food' — 'quantity' is required to maintain the unit comparison being made (one kilogram of beef versus the same amount of plant food). 'Weight' could technically work but 'quantity' is the more standard academic term in comparative nutritional and environmental analysis.",
        },
      ],
    },

    // Task 5: Reading & Writing Fill in the Blanks — Deep Learning AI
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions:
        "In the text below, some words are missing. For each blank, select the correct word from the dropdown menu.",
      rwfibText:
        "Deep learning, a subset of machine learning {{1}} on artificial neural networks with many layers, has driven the most dramatic advances in artificial intelligence over the past fifteen years, achieving human-level or superhuman performance on tasks that were previously considered to require uniquely human cognitive abilities. Unlike earlier rule-based AI systems that required programmers to explicitly encode domain knowledge, deep learning systems {{2}} their capabilities from vast datasets, automatically detecting patterns and representations at increasing levels of abstraction through successive layers of the network. The breakthrough that catalysed widespread adoption was the demonstration in 2012 that a deep convolutional neural network could substantially {{3}} existing algorithms on the ImageNet image recognition benchmark, reducing error rates by nearly half. Since then, deep learning has been applied with remarkable success to speech recognition, natural language processing, medical image analysis, drug {{4}}, autonomous vehicle navigation, and game-playing systems that have defeated world champions in Go and chess. However, deep learning systems are frequently criticised for their opacity: even their designers often cannot fully explain why a particular input produces a particular output, a characteristic that makes them difficult to {{5}} in high-stakes domains such as criminal sentencing, medical diagnosis, and financial lending, where decisions must be transparent and accountable. The field of explainable AI has {{6}} in response to these concerns, seeking to develop methods that make the reasoning of complex models interpretable to human users.",
      rwfibBlanks: [
        {
          id: 1,
          options: ["based", "founded", "built"],
          correct: "based",
          explanation:
            "'A subset of machine learning based on artificial neural networks' — 'based on' is the standard prepositional phrase for describing what something is derived from or built upon. 'Built on' is acceptable but less common in formal academic definitions; 'founded on' implies a more abstract principle.",
        },
        {
          id: 2,
          options: ["acquire", "develop", "learn"],
          correct: "learn",
          explanation:
            "'Deep learning systems learn their capabilities from vast datasets' — the defining characteristic of machine learning systems is that they 'learn' from data, and the term directly echoes the name 'deep learning.' 'Acquire' and 'develop' are less precise and do not capture the technical meaning.",
        },
        {
          id: 3,
          options: ["outperform", "surpass", "exceed"],
          correct: "outperform",
          explanation:
            "'Substantially outperform existing algorithms' — 'outperform' is the standard technical term in machine learning benchmarking for achieving better results than a competing system. 'Surpass' is closer to general language; 'exceed' typically applies to quantities or thresholds rather than competing systems.",
        },
        {
          id: 4,
          options: ["discovery", "development", "design"],
          correct: "discovery",
          explanation:
            "'Drug discovery' is the established technical term for the process of identifying new pharmaceutical compounds. 'Development' refers to the later stage of bringing a discovered drug to market; 'design' is more associated with rational drug design, a different approach.",
        },
        {
          id: 5,
          options: ["deploy", "trust", "justify"],
          correct: "deploy",
          explanation:
            "'Difficult to deploy in high-stakes domains' — the passage is discussing the practical challenge of implementing these opaque systems in consequential contexts. 'Deploy' (put into operational use) is the correct technical term. 'Trust' is too informal and subjective; 'justify' refers to explaining actions already taken.",
        },
        {
          id: 6,
          options: ["emerged", "grown", "developed"],
          correct: "emerged",
          explanation:
            "'The field of explainable AI has emerged in response to these concerns' — 'emerged' captures the idea of a new field coming into existence in response to a problem, which is the precise meaning intended. 'Grown' and 'developed' imply an already-established field expanding, whereas 'emerged' better conveys the appearance of something new.",
        },
      ],
    },
  ],
};
