import type { PTETest } from "./types";

export const pteReading15: PTETest = {
  id: "pte-reading-15",
  exam: "PTE",
  title: "PTE Academic Reading — Test 15",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "The Indus Valley Civilisation, which flourished in the Bronze Age across what is now Pakistan and northwest India from approximately 3300 to 1300 BCE, represents one of the ancient world's most sophisticated urban cultures. At its peak, it encompassed more than a thousand settlements, with major cities including Mohenjo-daro and Harappa reaching populations estimated at 40,000–80,000 inhabitants — making them among the largest urban centres on Earth at the time. The civilisation is remarkable for its advanced urban planning: cities featured grid-pattern streets, standardised fired brick construction, and an elaborate drainage and sewage system more sophisticated than those found in contemporary Mesopotamia or Egypt. Despite centuries of scholarship, the Indus script — a system of approximately 400 signs found on seals, pottery, and tablets — has resisted all attempts at decipherment, meaning that the civilisation's political structures, religious beliefs, and the reasons for its eventual decline remain matters of speculation.",
      stem: "What makes the Indus Valley Civilisation's drainage system particularly noteworthy?",
      options: [
        { label: "A", text: "It was the first sewage system ever constructed in human history." },
        { label: "B", text: "It was more advanced than those of other major civilisations of the same era." },
        { label: "C", text: "It was built entirely from stone rather than fired brick." },
        { label: "D", text: "It has been fully preserved and is still partially functional." },
      ],
      correct: "B",
      explanation: "The passage states the drainage system was 'more sophisticated than those found in contemporary Mesopotamia or Egypt' — more advanced than other civilisations of the time.",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "Chronic sleep deprivation — consistently sleeping fewer than seven hours per night — has been linked to a broad range of adverse health outcomes in large-scale epidemiological studies. Cognitive impairment is among the most immediate effects: even moderate sleep restriction produces deficits in attention, working memory, and decision-making that individuals often fail to recognise in themselves, as their subjective sense of alertness adjusts to the reduced sleep state. Long-term consequences are more severe: chronic short sleepers face significantly elevated risks of obesity, type 2 diabetes, cardiovascular disease, and depression. Mechanistically, inadequate sleep disrupts the secretion of hormones including cortisol, insulin, leptin, and ghrelin, impairs immune function, and reduces the brain's capacity to clear metabolic waste products via the glymphatic system. Adolescents are particularly vulnerable because the brain continues developing through the mid-twenties, and sleep plays a critical role in synaptic pruning and memory consolidation during this period. Despite widespread awareness of sleep's importance, structural factors — early school start times, workplace culture, and ubiquitous screen-based entertainment — continue to promote sleep insufficiency across industrialised societies.",
      stem: "Which TWO health consequences of chronic sleep deprivation are described in the passage?",
      options: [
        { label: "A", text: "Increased risk of type 2 diabetes" },
        { label: "B", text: "Reduced bone density" },
        { label: "C", text: "Elevated risk of cardiovascular disease" },
        { label: "D", text: "Impaired reproductive function" },
        { label: "E", text: "Higher incidence of skin conditions" },
      ],
      pickCount: 2,
      correct: ["A", "C"],
      explanation: "The passage explicitly lists 'type 2 diabetes' (A) and 'cardiovascular disease' (C) among the long-term risks of chronic sleep deprivation.",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "The earliest writing systems emerged independently in Mesopotamia, Egypt, and China, each developing from pictographic representations of objects and concepts toward more abstract phonetic systems." },
        { id: "s2", text: "In Mesopotamia, the pictographic proto-cuneiform evolved over centuries into the wedge-shaped cuneiform script, pressed into clay tablets, which could represent not only objects but also sounds and grammatical elements." },
        { id: "s3", text: "The Phoenician alphabet, developed around 1050 BCE, represented a radical simplification: rather than hundreds of logographic or syllabic signs, it used approximately 22 consonantal letters, each representing a single sound." },
        { id: "s4", text: "The Greeks adapted the Phoenician alphabet around 800 BCE, adding vowel signs to create the first fully phonemic alphabet — a system from which most modern European scripts derive." },
        { id: "s5", text: "Today's digital text, while transmitted through technologies unimaginable to ancient scribes, relies on the same fundamental principle: the representation of spoken language through a set of standardised visual symbols." },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation: "The sequence traces writing's development: emergence of first systems (s1) → evolution of cuneiform (s2) → Phoenician alphabet simplification (s3) → Greek adaptation with vowels (s4) → connection to modern digital text (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "Environmental psychology examines the relationship between the physical {{1}} and human behaviour, wellbeing, and cognitive functioning. Research in this field has demonstrated that exposure to natural {{2}} — parks, forests, bodies of water — reduces physiological stress markers including cortisol levels and blood pressure, and can restore {{3}} capacity depleted by prolonged focused work. The concept of 'attention restoration theory,' developed by Rachel and Stephen Kaplan, holds that natural environments engage {{4}} attention — a form of effortless fascination that allows directed attention to recover. Urban design increasingly incorporates these insights through the creation of green spaces, biophilic building design that incorporates natural materials and light, and efforts to reduce urban {{5}} such as traffic noise and air pollution.",
      wordBank: ["environment", "environments", "attentional", "involuntary", "stressors", "cognitive", "restorative", "artificial"],
      blanks: [
        { id: 1, correct: "environment", explanation: "Environmental psychology studies the relationship between 'the physical environment' and human behaviour." },
        { id: 2, correct: "environments", explanation: "Exposure to natural 'environments' — parks, forests, water — reduces stress markers." },
        { id: 3, correct: "attentional", explanation: "Natural environments restore 'attentional capacity' depleted by focused work." },
        { id: 4, correct: "involuntary", explanation: "Attention restoration theory holds that nature engages 'involuntary attention' — effortless fascination." },
        { id: 5, correct: "stressors", explanation: "Urban design aims to reduce 'urban stressors' such as traffic noise and air pollution." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "Environmental regulation seeks to {{1}} the negative externalities of economic activity on ecosystems and human health. The concept of an externality refers to a cost or benefit that {{2}} parties — those not directly involved in a transaction — bear without compensation. Pollution is the classic negative externality: a factory that discharges waste into a river {{3}} costs on downstream communities without paying for them. Regulatory {{4}} include emissions standards, pollution permits that can be traded between firms, and environmental taxes designed to make the cost of pollution {{5}} in market prices. The effectiveness of regulation depends critically on enforcement {{6}}: weak monitoring and low penalties create incentives for non-compliance, particularly where the profits from polluting activities exceed the expected cost of sanctions.",
      rwfibBlanks: [
        { id: 1, options: ["address", "ignore", "measure", "promote"], correct: "address", explanation: "Environmental regulation seeks to 'address' negative externalities — deal with and correct them." },
        { id: 2, options: ["third", "first", "second", "external"], correct: "third", explanation: "'Third parties' — those outside the transaction — bear externality costs without compensation." },
        { id: 3, options: ["imposes", "avoids", "reduces", "measures"], correct: "imposes", explanation: "A factory 'imposes costs on downstream communities' — forces them to bear costs." },
        { id: 4, options: ["instruments", "failures", "objectives", "barriers"], correct: "instruments", explanation: "'Regulatory instruments' include standards, permits, and taxes — the tools of environmental regulation." },
        { id: 5, options: ["reflected", "hidden", "reduced", "exaggerated"], correct: "reflected", explanation: "Taxes make pollution costs 'reflected in market prices' — visible and incorporated into economic decisions." },
        { id: 6, options: ["capacity", "strategy", "history", "ambition"], correct: "capacity", explanation: "'Enforcement capacity' — the ability to monitor and penalise violations — determines regulatory effectiveness." },
      ],
    },
  ],
};
