import type { WritingTest } from "./writing-types";

export const pteWriting25: WritingTest = {
  id: "pte-writing-25",
  exam: "PTE",
  title: "PTE Academic Writing — Test 25",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "pte_swt",
      taskLabel: "Task 1 — Summarise Written Text",
      instructions:
        "Read the passage below and summarise it using one sentence. Type your response in the box. You have 10 minutes to finish this task. Your response will be judged on the quality of your writing and on how well your response presents the key points in the passage.",
      timeSeconds: 600,
      minWords: 5,
      maxWords: 75,
      prompt: "Write a single sentence (5–75 words) that summarises the passage below.",
      passage: `Electric vehicles have gained considerable momentum as a central pillar of national and corporate strategies to reduce transportation-related carbon emissions, which account for approximately twenty-three percent of global greenhouse gas output. Proponents highlight the substantial lifecycle emissions advantage of battery electric vehicles over internal combustion engine counterparts, particularly as electricity grids progressively incorporate renewable energy sources. Studies indicate that, even when accounting for the carbon intensity of battery manufacturing, an electric vehicle typically achieves a lower carbon footprint than a petrol equivalent within two to four years of use. However, critics point to several important limitations. Battery production relies on lithium, cobalt, and nickel extraction, which carries significant environmental and human rights concerns in mining regions. Charging infrastructure remains inadequate in rural and lower-income areas, limiting accessibility. Furthermore, in countries where coal dominates electricity generation, the emissions benefit of electric vehicles is markedly reduced. These constraints suggest that while electric vehicle adoption is a meaningful component of decarbonisation, it must be accompanied by grid decarbonisation, responsible mineral sourcing, and broader modal shifts towards public transport to achieve transformative climate outcomes.`,
      modelAnswer: `Electric vehicles offer a meaningful but qualified solution to transport emissions: while their lifecycle carbon footprint is generally lower than petrol vehicles — especially as grids decarbonise — the environmental benefits are constrained by coal-heavy electricity sources, ethically problematic battery mineral extraction, and insufficient charging infrastructure in rural and lower-income communities, necessitating complementary decarbonisation strategies.`,
      bandDescriptors: [
        {
          criterion: "Content",
          band7: "Summarises the main points of the passage; may include minor details or omit one key idea.",
          band8: "Accurately captures the key points of the passage in a concise and well-balanced sentence.",
        },
        {
          criterion: "Form",
          band7: "Response is written as a single sentence and falls within the 5–75 word limit.",
          band8: "Response is a single, grammatically complete sentence within the word limit.",
        },
        {
          criterion: "Grammar",
          band7: "Uses appropriate grammar with minor errors that do not impede comprehension.",
          band8: "Grammatically accurate and fluent; demonstrates control of complex sentence structures.",
        },
        {
          criterion: "Vocabulary",
          band7: "Uses appropriate vocabulary; some paraphrasing of source language.",
          band8: "Effective paraphrasing; precise vocabulary choices that reflect understanding of the passage.",
        },
      ],
    },
    {
      id: 2,
      type: "pte_essay",
      taskLabel: "Task 2 — Write Essay",
      instructions:
        "You will have 20 minutes to plan, write and revise an essay about the topic below. Your response will be judged on how well you develop a position, organise your ideas, present supporting details, and control the elements of standard written English. You should write 200–300 words.",
      timeSeconds: 1200,
      minWords: 200,
      maxWords: 300,
      prompt:
        "Tourism has both positive and negative effects on local communities. Discuss both views and give your own opinion.",
      modelAnswer: `Tourism is one of the world's largest industries, and its effects on host communities are complex and multifaceted. While it generates significant economic benefits, it also carries social and environmental costs that deserve careful consideration.

On the positive side, tourism creates employment and stimulates local economies. Hotels, restaurants, transport providers, and artisans all benefit from visitor expenditure, and tax revenues generated by the tourism sector can fund public infrastructure such as roads, hospitals, and schools. Cultural tourism can also revitalise interest in traditional arts, languages, and festivals, helping communities preserve and celebrate their heritage.

However, the negative consequences are equally significant. Mass tourism frequently drives up property prices, making housing unaffordable for long-term residents and displacing established communities — a process evident in cities such as Barcelona, Venice, and Lisbon. Fragile ecosystems, including coral reefs, mountain trails, and heritage sites, suffer physical degradation when visitor numbers exceed carrying capacity. Furthermore, the commercialisation of local culture can lead to the erosion of authentic traditions, replacing genuine practice with superficial performances designed for tourist consumption.

In my opinion, the key to maximising tourism's benefits while minimising its harms lies in robust regulatory frameworks. Governments and local authorities should enforce visitor limits at sensitive sites, implement tourist taxes that fund conservation and affordable housing, and incentivise community-based tourism models that distribute economic benefits more equitably.

In conclusion, tourism's impact on local communities depends largely on how effectively it is managed, and thoughtful policy is essential to ensuring that benefits outweigh the costs.`,
      bandDescriptors: [
        {
          criterion: "Content",
          band7: "Addresses the task prompt; presents main ideas with some development; may lack full balance or depth in one area.",
          band8: "Addresses the prompt fully; presents a well-balanced discussion with clear personal opinion; ideas are well-developed.",
        },
        {
          criterion: "Form",
          band7: "Response falls within or close to the 200–300 word range; organised in clear paragraphs.",
          band8: "Response meets the word requirement; paragraphing is effective and logical.",
        },
        {
          criterion: "Grammar",
          band7: "Good grammatical control; range of structures; minor errors that do not affect meaning.",
          band8: "Accurate and varied grammar; complex structures used effectively; very few errors.",
        },
        {
          criterion: "Vocabulary",
          band7: "Appropriate range of vocabulary; some flexibility; occasional minor word choice issues.",
          band8: "Wide and precise vocabulary; fluent expression; very few lexical errors.",
        },
      ],
    },
  ],
};
