import type { PTETest } from "./types";

export const pteReading11: PTETest = {
  id: "pte-reading-11",
  exam: "PTE",
  title: "PTE Academic Reading — Test 11",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "Behavioural economics emerged as a discipline in the late twentieth century by challenging the foundational assumption of classical economics that individuals make rational decisions that maximise their utility. Researchers including Daniel Kahneman and Amos Tversky demonstrated through extensive experimental work that human decision-making is systematically influenced by cognitive biases and heuristics — mental shortcuts that can produce predictable errors. Prospect theory, for which Kahneman received the Nobel Prize in Economic Sciences in 2002, shows that people evaluate outcomes relative to a reference point rather than in absolute terms, and that losses loom larger than equivalent gains — a phenomenon known as loss aversion. Anchoring describes the tendency to rely too heavily on the first piece of information encountered when making decisions. The availability heuristic causes people to overestimate the probability of events that come easily to mind, such as dramatic accidents or crimes reported extensively in the media. These insights have been applied in policy design, marketing, healthcare, and finance to predict and sometimes improve human decision-making.",
      stem: "What is 'loss aversion' as described in the passage?",
      options: [
        { label: "A", text: "The tendency to avoid making any financial decisions under uncertainty." },
        { label: "B", text: "The human preference for gains over losses of equal value." },
        { label: "C", text: "The tendency to weight potential losses more heavily than equivalent gains." },
        { label: "D", text: "The error of overestimating the probability of financial loss." },
      ],
      correct: "C",
      explanation: "The passage defines loss aversion as the phenomenon that 'losses loom larger than equivalent gains' — potential losses are weighted more heavily than equal gains.",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "The question of how best to learn a second language has been debated by linguists and educators for decades. The dominant approach in formal education through much of the twentieth century was the grammar-translation method, in which students learned grammatical rules and vocabulary lists and translated texts between languages. From the 1970s onward, communicative language teaching (CLT) gained ascendancy, emphasising meaningful interaction in the target language over explicit grammar instruction. Research into language acquisition has provided some clarity: comprehensible input — exposure to language that is slightly beyond the learner's current level — appears to be essential for acquisition, as proposed by Stephen Krashen's Input Hypothesis. Output — the production of the target language through speaking and writing — also plays a role, particularly in forcing learners to notice gaps in their knowledge. Motivation is consistently identified as one of the strongest predictors of language learning success, as is the quantity of contact with the target language outside formal instruction. Age is a factor: children who begin learning before puberty generally achieve higher levels of phonological fluency, though adults are often more efficient learners of grammar and vocabulary in the short term.",
      stem: "Which TWO factors does the passage identify as important predictors of language learning success?",
      options: [
        { label: "A", text: "Using the grammar-translation method" },
        { label: "B", text: "Learner motivation" },
        { label: "C", text: "Beginning study before the age of five" },
        { label: "D", text: "Quantity of contact with the target language" },
        { label: "E", text: "Having a native-speaking teacher" },
      ],
      pickCount: 2,
      correct: ["B", "D"],
      explanation: "The passage explicitly states 'Motivation is consistently identified as one of the strongest predictors' (B) and 'the quantity of contact with the target language outside formal instruction' (D).",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "The history of computing can be traced to Charles Babbage's designs for mechanical calculating engines in the early nineteenth century, though these were never fully constructed during his lifetime." },
        { id: "s2", text: "The Second World War accelerated electronic computing dramatically: Alan Turing's theoretical work on computation and the practical development of machines like Colossus — used to break German military codes — established the foundations of programmable electronic computing." },
        { id: "s3", text: "The invention of the transistor at Bell Laboratories in 1947 replaced bulky and unreliable vacuum tubes, enabling computers to shrink dramatically in size while increasing in reliability and speed." },
        { id: "s4", text: "The development of the integrated circuit in the late 1950s, and the subsequent application of Moore's Law — the observation that transistor density roughly doubles every two years — drove exponential improvements in computing power across the following decades." },
        { id: "s5", text: "The internet, the smartphone, and artificial intelligence represent the latest stages of a trajectory that began with mechanical gears and now encompasses machines capable of performing tasks once considered uniquely human." },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation: "The sequence follows computing history chronologically: Babbage (s1) → wartime electronic computing (s2) → transistor (s3) → integrated circuit and Moore's Law (s4) → internet and AI era (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "Isaac Newton's three laws of motion, published in his Principia Mathematica in 1687, provided the {{1}} framework for understanding the physical world for over two centuries. The first law — the law of {{2}} — states that an object at rest remains at rest, and an object in motion continues in motion at the same speed and direction, unless acted upon by an external force. The second law establishes the relationship between force, mass, and {{3}}, expressed as F = ma. The third law holds that for every action there is an equal and {{4}} reaction. Newton's framework was eventually shown to be incomplete by Einstein's theory of relativity, which applies at very high speeds or in strong {{5}} fields, but remains accurate and sufficient for the vast majority of everyday engineering applications.",
      wordBank: ["foundational", "inertia", "acceleration", "opposite", "gravitational", "velocity", "momentum", "classical"],
      blanks: [
        { id: 1, correct: "foundational", explanation: "Newton's laws provided the 'foundational framework' — the essential basis — for classical physics." },
        { id: 2, correct: "inertia", explanation: "The first law is the law of 'inertia' — objects resist changes in their state of motion." },
        { id: 3, correct: "acceleration", explanation: "F = ma relates force, mass, and 'acceleration' — this is Newton's second law." },
        { id: 4, correct: "opposite", explanation: "Newton's third law: 'equal and opposite reaction' is the exact phrasing." },
        { id: 5, correct: "gravitational", explanation: "Einstein's relativity applies in strong 'gravitational' fields — near massive objects." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "International migration — the movement of people across national {{1}} — is one of the most politically and economically consequential phenomena of the contemporary world. People migrate for a variety of reasons, commonly {{2}} as push factors (conditions in the country of origin that motivate departure, such as conflict, poverty, or environmental degradation) and pull factors (conditions in the destination country that attract migrants, such as economic {{3}}, political stability, or family reunion). High-income countries have increasingly relied on {{4}} migration to address labour shortages in sectors ranging from healthcare to agriculture. While evidence consistently shows that migration generates net economic {{5}} for receiving countries, public concern about cultural {{6}} and pressure on public services has made immigration policy one of the most divisive political issues across the developed world.",
      rwfibBlanks: [
        { id: 1, options: ["borders", "regions", "cities", "continents"], correct: "borders", explanation: "International migration is defined by movement across national 'borders' — the boundaries between countries." },
        { id: 2, options: ["categorised", "described", "ignored", "measured"], correct: "categorised", explanation: "Migration reasons are 'categorised' as push and pull factors — organised into these two categories." },
        { id: 3, options: ["opportunity", "instability", "inequality", "growth"], correct: "opportunity", explanation: "Economic 'opportunity' in the destination country is a classic pull factor for migrants." },
        { id: 4, options: ["skilled", "illegal", "seasonal", "temporary"], correct: "skilled", explanation: "High-income countries rely on 'skilled' migration to address labour shortages in specialised sectors." },
        { id: 5, options: ["benefits", "costs", "risks", "burdens"], correct: "benefits", explanation: "Evidence shows migration generates net economic 'benefits' for receiving countries — positive economic outcomes." },
        { id: 6, options: ["change", "exchange", "diversity", "conflict"], correct: "change", explanation: "Concern about 'cultural change' — shifts in cultural identity — is a common driver of anti-immigration sentiment." },
      ],
    },
  ],
};
