import type { PTETest } from "./types";

export const pteReading14: PTETest = {
  id: "pte-reading-14",
  exam: "PTE",
  title: "PTE Academic Reading — Test 14",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "Marine protected areas (MPAs) are designated zones of ocean where human activities such as fishing, mining, and tourism are regulated or prohibited in order to allow marine ecosystems to recover and thrive. As of 2023, approximately 8 percent of the world's oceans were designated as protected areas, though scientists and conservation organisations have argued that coverage of at least 30 percent is necessary to stem biodiversity loss — a target endorsed by the Kunming-Montreal Global Biodiversity Framework adopted in December 2022. The effectiveness of MPAs varies considerably depending on the level of protection afforded, the quality of enforcement, and the ecological condition of the area at the time of designation. Fully protected 'no-take' zones, where all extractive activities are prohibited, consistently show the strongest ecological recovery, with fish biomass inside well-enforced reserves averaging five times higher than in surrounding unprotected waters. However, many designated MPAs are 'paper parks' — areas formally protected on maps but receiving little or no enforcement in practice.",
      stem: "Why do scientists argue that more than 8 percent of the ocean needs to be protected?",
      options: [
        { label: "A", text: "The current MPAs are too small to support migratory species." },
        { label: "B", text: "Higher coverage is needed to effectively prevent biodiversity loss." },
        { label: "C", text: "More MPAs would increase tourism revenue in coastal countries." },
        { label: "D", text: "The current MPAs are located in the wrong geographic regions." },
      ],
      correct: "B",
      explanation: "The passage states scientists argue 'coverage of at least 30 percent is necessary to stem biodiversity loss' — higher coverage is needed to stop biodiversity decline.",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "The digital divide in education has become an acute concern, particularly following the shift to remote learning during the COVID-19 pandemic. Students from low-income households who lacked reliable internet access and devices fell significantly behind their peers in countries where schooling moved online. Research has shown that the consequences of this gap are not merely short-term: disrupted schooling during formative years has long-lasting effects on literacy, numeracy, and ultimately on lifetime earnings and social mobility. The problem is compounded in rural and remote areas, where both physical connectivity infrastructure and the availability of qualified teachers are often inadequate. Promising interventions include one-to-one device programmes, subsidised broadband for low-income families, teacher training in effective digital pedagogy, and the development of offline-capable educational applications for contexts where reliable connectivity cannot be assumed. Critics of technology-focused solutions caution that without accompanying investment in teacher quality, curriculum design, and school leadership, devices and connectivity alone will not close achievement gaps.",
      stem: "Which TWO interventions to address the educational digital divide are mentioned in the passage?",
      options: [
        { label: "A", text: "Building more schools in rural areas" },
        { label: "B", text: "One-to-one device programmes" },
        { label: "C", text: "Reducing class sizes in low-income schools" },
        { label: "D", text: "Subsidised broadband for low-income families" },
        { label: "E", text: "International student exchange programmes" },
      ],
      pickCount: 2,
      correct: ["B", "D"],
      explanation: "The passage explicitly lists 'one-to-one device programmes' (B) and 'subsidised broadband for low-income families' (D) among promising interventions.",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "Gregor Mendel's experiments with pea plants in the 1860s established the foundational laws of inheritance, demonstrating that traits are passed from parents to offspring in predictable ratios through discrete units later termed genes." },
        { id: "s2", text: "The discovery of DNA's double helix structure by Watson, Crick, Franklin, and Wilkins in 1953 revealed the physical mechanism by which genetic information is stored and replicated." },
        { id: "s3", text: "The Human Genome Project, completed in 2003, mapped the approximately 3 billion base pairs of human DNA, providing a reference genome that has since underpinned advances in medicine, forensics, and evolutionary biology." },
        { id: "s4", text: "The development of CRISPR-Cas9 gene editing technology from 2012 onward transformed the field by enabling precise, targeted modifications to DNA sequences in living organisms at relatively low cost and with high efficiency." },
        { id: "s5", text: "Genetics now stands at the centre of personalised medicine, with genomic sequencing increasingly used to identify disease risk, guide drug prescribing, and develop targeted cancer therapies." },
      ],
      correctOrder: ["s1", "s2", "s3", "s4", "s5"],
      reorderExplanation: "The sequence is chronological: Mendel's laws (s1) → DNA structure (s2) → Human Genome Project (s3) → CRISPR editing (s4) → current applications in personalised medicine (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "The human brain contains approximately 86 billion {{1}}, each forming thousands of connections called {{2}} with neighbouring cells. The brain is organised into distinct regions with specialised functions: the prefrontal cortex is responsible for executive functions including planning, decision-making, and {{3}} control; the hippocampus plays a central role in the formation of new memories; and the amygdala processes emotional responses, particularly {{4}} and threat detection. Communication between neurons occurs via electrical signals that trigger the release of chemical {{5}} across synaptic gaps, enabling the rapid transmission of information throughout the brain and body.",
      wordBank: ["neurons", "synapses", "impulse", "fear", "neurotransmitters", "inhibitory", "cognitive", "dendrites"],
      blanks: [
        { id: 1, correct: "neurons", explanation: "The brain contains 'neurons' — the nerve cells that form the basis of neural processing." },
        { id: 2, correct: "synapses", explanation: "Neurons form 'synapses' — connection points — with neighbouring cells." },
        { id: 3, correct: "cognitive", explanation: "The prefrontal cortex handles executive functions including 'cognitive control' — regulation of thought and behaviour." },
        { id: 4, correct: "fear", explanation: "The amygdala processes emotional responses 'particularly fear and threat detection.'" },
        { id: 5, correct: "neurotransmitters", explanation: "Chemical 'neurotransmitters' are released across synaptic gaps to transmit signals between neurons." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "Access to quality education remains deeply {{1}} across and within nations. Children born into poverty face multiple {{2}} to educational achievement: inadequate nutrition affects cognitive development; poor housing disrupts sleep and study; parental employment instability limits time for engagement with children's learning. Schools in low-income communities are frequently {{3}} resourced, with larger class sizes, less experienced teachers, and inferior physical infrastructure compared to schools in wealthier areas. Evidence-based interventions including early childhood education, targeted tutoring, and extended school days have shown {{4}} results in narrowing achievement gaps, but require sustained political will and funding to implement at {{5}}. The role of higher education in providing {{6}} mobility remains significant, though rising tuition costs have made university increasingly {{7}} for students from disadvantaged backgrounds.",
      rwfibBlanks: [
        { id: 1, options: ["unequal", "available", "valuable", "contested"], correct: "unequal", explanation: "Access to quality education is 'unequal' across and within nations — distributed unevenly." },
        { id: 2, options: ["barriers", "solutions", "advantages", "pressures"], correct: "barriers", explanation: "Children in poverty face 'barriers to educational achievement' — obstacles that impede progress." },
        { id: 3, options: ["under", "over", "well", "fairly"], correct: "under", explanation: "Schools in low-income areas are 'under-resourced' — lacking adequate resources." },
        { id: 4, options: ["promising", "mixed", "limited", "unproven"], correct: "promising", explanation: "Evidence-based interventions have shown 'promising results' — encouraging early evidence of effectiveness." },
        { id: 5, options: ["scale", "speed", "quality", "cost"], correct: "scale", explanation: "Interventions must be implemented 'at scale' — across the full system, not just in pilots." },
        { id: 6, options: ["social", "economic", "academic", "cultural"], correct: "social", explanation: "Higher education provides 'social mobility' — movement between social and economic classes." },
        { id: 7, options: ["inaccessible", "popular", "competitive", "essential"], correct: "inaccessible", explanation: "Rising tuition costs have made university 'increasingly inaccessible' for disadvantaged students." },
      ],
    },
  ],
};
