import type { PTEListeningTest } from "./pte-listening-types";

const test20: PTEListeningTest = {
  id: "pte-listening-20",
  title: "PTE Listening — Test 20",
  totalMinutes: 45,

  // ── Summarise Spoken Text (1 task) ──────────────────────────────────────────
  summariseSpokenText: [
    {
      id: "sst-20-1",
      type: "summarise_spoken_text",
      wordMin: 50,
      wordMax: 70,
      responseSeconds: 600,
      topic: "Soil Science and Carbon Sequestration",
      audioUrl: "",
      audioText: "Soil is one of the planet's most complex and vital natural resources, supporting food production, filtering water, and regulating the global carbon cycle. A single teaspoon of healthy soil can contain billions of microorganisms including bacteria, fungi, and protozoa, which drive the decomposition of organic matter and the recycling of nutrients. Soils store approximately twice as much carbon as the atmosphere, making their management critical to climate change mitigation. However, land degradation through intensive agriculture, deforestation, and urbanisation releases stored carbon and reduces the soil's capacity to support plant life. Practices such as cover cropping, reduced tillage, and the application of biochar — a form of charcoal produced from plant material — can restore soil organic matter and increase carbon storage. International efforts are now underway to incorporate soil carbon sequestration into national climate commitments under the Paris Agreement.",
    },
  ],

  // ── Multiple Choice Multiple Answer (2 tasks) ────────────────────────────────
  mcMulti: [
    {
      id: "mcm-20-1",
      type: "mc_multi",
      audioUrl: "",
      audioText: "The relationship between globalisation and inequality has been debated extensively by economists and policymakers. At the global level, the integration of developing economies into world trade has lifted hundreds of millions of people out of extreme poverty, particularly in East and South-East Asia. However, within many high-income countries, workers in manufacturing industries have faced wage stagnation and job displacement as production shifted to lower-cost locations. Trade agreements have generally liberalised the movement of goods and capital but have been less successful at facilitating the free movement of workers. The digital economy creates new opportunities but also concentrates profits among a small number of highly educated workers and technology firms. Redistribution through taxation and public investment remains a key policy lever for addressing inequality generated by globalisation.",
      question: "According to the talk, which TWO effects of globalisation are discussed?",
      options: [
        "Reduction in extreme poverty in developing economies",
        "Increased diplomatic tensions between trading nations",
        "Wage stagnation and job losses in manufacturing in high-income countries",
        "Collapse of global financial institutions",
        "Growth of agricultural exports from sub-Saharan Africa",
        "Reduction in carbon emissions due to more efficient production",
      ],
      correctIndexes: [0, 2],
    },
    {
      id: "mcm-20-2",
      type: "mc_multi",
      audioUrl: "",
      audioText: "Political philosophy examines fundamental questions about the nature and justification of political authority, the rights and obligations of citizens, and the principles that should govern the distribution of benefits and burdens in society. Liberalism holds that individuals have rights that the state must respect, and that government authority requires justification in terms acceptable to all citizens. Communitarianism challenges the liberal emphasis on the individual, arguing that identity and moral obligations are rooted in particular communities and traditions rather than abstract universal principles. Republicanism emphasises freedom from domination and civic participation as conditions for genuine political liberty. Contemporary debates in political philosophy address topics including distributive justice, global governance, the rights of future generations, and the ethics of civil disobedience.",
      question: "Which THREE philosophical traditions or concerns are explicitly discussed in the recording?",
      options: [
        "Liberalism and individual rights",
        "Anarchism and the abolition of the state",
        "Communitarianism and community-based identity",
        "Republicanism and freedom from domination",
        "Utilitarianism and the maximisation of happiness",
        "Marxism and class struggle",
      ],
      correctIndexes: [0, 2, 3],
    },
  ],

  // ── Fill in the Blanks (2 tasks) ─────────────────────────────────────────────
  fillBlanks: [
    {
      id: "fib-20-1",
      type: "fill_blanks",
      audioUrl: "",
      audioText: "Aeronautical engineering encompasses the design, development, testing, and production of aircraft and related systems. The fundamental challenge of flight is overcoming gravity and drag while generating sufficient lift and thrust. Lift is produced when air flowing over an aerofoil shape creates lower pressure above the wing than below, generating an upward force. Thrust is provided by engines, which may be piston-driven, turbofan, or rocket-based depending on the application. Modern commercial aircraft are designed with computerised fly-by-wire control systems that replace mechanical linkages with electronic signals, improving responsiveness and reducing aircraft weight.",
      transcript: "Aeronautical engineering encompasses the design, development, testing, and production of aircraft and related systems. The fundamental challenge of flight is overcoming ___BLANK___ and drag while generating sufficient lift and thrust. Lift is produced when air flowing over an aerofoil shape creates lower ___BLANK___ above the wing than below, generating an upward force. ___BLANK___ is provided by engines, which may be piston-driven, turbofan, or rocket-based. Modern commercial aircraft use computerised fly-by-wire control systems that replace mechanical linkages with electronic ___BLANK___.",
      answers: ["gravity", "pressure", "Thrust", "signals"],
    },
    {
      id: "fib-20-2",
      type: "fill_blanks",
      audioUrl: "",
      audioText: "Indigenous knowledge systems represent accumulated understandings of local environments, species, weather patterns, and land management practices developed by communities over generations. These knowledge systems have proved invaluable in fields including conservation biology, sustainable agriculture, and medicine, often guiding scientists to plants and practices with therapeutic or ecological value. However, indigenous knowledge has frequently been marginalised or appropriated without recognition or benefit sharing. International frameworks, including the Convention on Biological Diversity's Nagoya Protocol, now require that companies and researchers obtain prior informed consent from communities and share benefits arising from the use of their knowledge and genetic resources.",
      transcript: "Indigenous knowledge systems represent accumulated understandings of local environments, species, weather patterns, and land ___BLANK___ practices developed by communities over generations. These knowledge systems have proved invaluable in fields including conservation biology, sustainable agriculture, and medicine, often guiding scientists to plants with therapeutic or ___BLANK___ value. However, indigenous knowledge has frequently been marginalised or ___BLANK___ without recognition or benefit sharing. International frameworks now require that companies obtain prior informed ___BLANK___ from communities before using their knowledge and genetic resources.",
      answers: ["management", "ecological", "appropriated", "consent"],
    },
  ],

  // ── Highlight Correct Summary (2 tasks) ─────────────────────────────────────
  highlightSummary: [
    {
      id: "hcs-20-1",
      type: "highlight_summary",
      audioUrl: "",
      audioText: "Trade economics analyses the patterns, causes, and consequences of the exchange of goods and services between countries. The theory of comparative advantage, developed by David Ricardo in the nineteenth century, holds that countries benefit from specialising in the production of goods they can produce at relatively lower cost and trading for others, even if one country is more efficient at producing everything. In practice, trade patterns are shaped not only by comparative advantage but also by geography, natural resources, historical relationships, and government policies including tariffs, subsidies, and trade agreements. The gains from trade are real but unevenly distributed, which is a central source of political tension around trade liberalisation.",
      correctIndex: 2,
      summaries: [
        "Trade economics has demonstrated that free trade always increases prosperity for all countries involved equally, and that tariffs and subsidies are universally harmful to economic growth.",
        "The theory of comparative advantage holds that only countries that are efficient at producing goods should engage in international trade, while less productive nations should focus on domestic self-sufficiency.",
        "Trade economics explains that countries gain from specialising in relatively lower-cost goods and trading, though real-world trade is also shaped by geography, policy, and history, and gains are unevenly distributed.",
        "Trade economics shows that modern trade agreements have eliminated comparative advantage as a factor in determining trade patterns, replacing it with strategic considerations driven by multinational corporations.",
      ],
    },
    {
      id: "hcs-20-2",
      type: "highlight_summary",
      audioUrl: "",
      audioText: "Gene editing technologies, particularly CRISPR-Cas9, have transformed the ability of scientists to make precise modifications to DNA sequences. CRISPR works by using a guide RNA to direct the Cas9 protein to a specific location in the genome, where it cuts the DNA. The cell's natural repair mechanisms then either disable the gene or, if a template is provided, introduce a desired sequence. Applications in medicine include potential treatments for inherited genetic diseases such as sickle cell anaemia and beta thalassaemia, with early clinical trials showing promising results. In agriculture, gene-edited crops have been developed with improved resistance to drought and disease. The technology also raises ethical questions about the possibility of germline editing, which would pass modifications to future generations.",
      correctIndex: 1,
      summaries: [
        "Gene editing using CRISPR has been approved for routine clinical use in most countries and is now considered a standard treatment for all inherited genetic diseases, replacing traditional transplant procedures.",
        "CRISPR-Cas9 allows precise DNA modifications with applications in treating genetic diseases and developing resilient crops, though germline editing that passes changes to future generations raises significant ethical concerns.",
        "Gene editing technologies such as CRISPR are primarily used in agriculture to produce herbicide-resistant crops for large-scale commercial farming, with medical applications still decades away from clinical use.",
        "CRISPR works by permanently deleting entire chromosomes from human cells, a process that has cured hundreds of inherited conditions but also caused unexpected side effects in a significant proportion of patients.",
      ],
    },
  ],

  // ── Multiple Choice Single Answer (2 tasks) ──────────────────────────────────
  mcSingle: [
    {
      id: "mcs-20-1",
      type: "mc_single",
      audioUrl: "",
      audioText: "The philosophy of mind addresses questions about the nature of mental states, their relationship to the physical brain, and what it means to be conscious. The mind-body problem asks how subjective experiences — what it is like to feel pain, see red, or taste coffee — can arise from physical processes in the brain. Physicalist theories hold that mental states are identical to or realised by brain states, and that a complete description of the brain would include everything there is to know about the mind. Dualist theories maintain that the mind is a distinct non-physical entity that interacts with the body. The hard problem of consciousness, identified by the philosopher David Chalmers, asks why any physical process should give rise to subjective experience at all.",
      question: "What is the hard problem of consciousness as described by the speaker?",
      options: [
        "The difficulty of explaining why the human brain is more complex than that of other animals.",
        "The challenge of measuring conscious states using existing neuroscientific technology.",
        "The question of why physical brain processes give rise to subjective experience.",
        "The problem of demonstrating that animals other than humans are genuinely conscious.",
      ],
      correctIndex: 2,
    },
    {
      id: "mcs-20-2",
      type: "mc_single",
      audioUrl: "",
      audioText: "Climate adaptation refers to the adjustments that individuals, communities, and governments make in response to actual or anticipated climate change and its effects. Unlike mitigation, which seeks to reduce greenhouse gas emissions and limit future warming, adaptation accepts that some degree of climate change is already locked in and focuses on managing its consequences. Adaptation measures include constructing coastal flood defences, developing drought-resistant crop varieties, redesigning urban spaces to reduce the urban heat island effect, and improving early warning systems for extreme weather events. Developing countries often face the greatest adaptation challenges because they are most exposed to climate risks while having the fewest financial and institutional resources to respond.",
      question: "How does the speaker distinguish adaptation from mitigation?",
      options: [
        "Adaptation involves removing carbon from the atmosphere while mitigation prevents new emissions.",
        "Adaptation manages the consequences of climate change already underway, while mitigation seeks to reduce future emissions.",
        "Adaptation is practised only by developing countries, while mitigation is the responsibility of industrialised nations.",
        "Adaptation focuses on long-term planning, while mitigation responds to immediate climate disasters.",
      ],
      correctIndex: 1,
    },
  ],

  // ── Select Missing Word (2 tasks) ────────────────────────────────────────────
  selectMissingWord: [
    {
      id: "smw-20-1",
      type: "select_missing_word",
      audioUrl: "",
      audioText: "Space colonisation presents one of the most ambitious long-term projects in human history. Advocates argue that establishing permanent human settlements beyond Earth would provide insurance against extinction-level catastrophes, expand access to resources, and drive technological innovation. Mars is considered the most viable initial target because its day length and axial tilt are similar to Earth's, and evidence suggests it once had liquid water on its surface. However, the radiation environment, the thin carbon dioxide atmosphere, and the extreme cold pose formidable challenges to human survival. Sustained investment and international cooperation will be essential to make interplanetary",
      options: ["communication possible", "settlement viable", "tourism profitable", "research redundant"],
      correctIndex: 1,
    },
    {
      id: "smw-20-2",
      type: "select_missing_word",
      audioUrl: "",
      audioText: "Political philosophy's concept of justice extends beyond procedural fairness to questions about what outcomes a just society should produce. John Rawls argued that principles of justice should be chosen from behind a veil of ignorance, where individuals do not know their place in society, their social class, or their natural abilities. He concluded that rational agents in this position would select principles that protect basic liberties and arrange inequalities so that they benefit the least advantaged members of society. This framework has been enormously influential but also widely contested, with critics arguing that it places too many constraints on individual",
      options: ["freedom", "education", "expression", "taxation"],
      correctIndex: 0,
    },
  ],

  // ── Highlight Incorrect Words (2 tasks) ──────────────────────────────────────
  highlightIncorrect: [
    {
      id: "hiw-20-1",
      type: "highlight_incorrect",
      audioUrl: "",
      audioText: "Soil carbon sequestration involves increasing the amount of carbon stored in agricultural and natural soils by changing land management practices. Cover crops, which are planted between main crop cycles, add organic matter to the soil when they are incorporated. Reduced tillage limits the disruption of soil structure and slows the release of stored carbon into the atmosphere. Biochar, produced by heating plant material in the absence of oxygen, is highly resistant to decomposition and can store carbon in soil for centuries.",
      displayText: "Soil carbon sequestration involves increasing the amount of carbon stored in agricultural and natural soils by changing land management practices. Cover crops, which are planted between main crop cycles, add organic matter to the soil when they are ploughed in. Reduced tillage limits the disruption of soil structure and slows the emission of stored carbon into the atmosphere. Biochar, produced by heating plant material in the absence of oxygen, is highly resistant to decomposition and can store carbon in soil for centuries.",
      incorrectIndexes: [38, 51],
    },
    {
      id: "hiw-20-2",
      type: "highlight_incorrect",
      audioUrl: "",
      audioText: "The theory of comparative advantage predicts that free trade will increase total output by allowing countries to specialise in activities where their opportunity costs are lowest. Even if one country is more efficient at producing every good, both countries can gain from trade provided that the relative costs of production differ between them. This insight underpins the economic case for trade liberalisation and the reduction of tariffs and trade barriers.",
      displayText: "The theory of comparative advantage predicts that free trade will increase total output by allowing countries to specialise in activities where their production costs are lowest. Even if one country is more efficient at producing every good, both countries can benefit from trade provided that the relative costs of production differ between them. This insight underpins the economic case for trade liberalisation and the reduction of tariffs and trade barriers.",
      incorrectIndexes: [22, 40],
    },
  ],

  // ── Write from Dictation (3 tasks) ───────────────────────────────────────────
  writeDictation: [
    {
      id: "wfd-20-1",
      type: "write_dictation",
      audioUrl: "",
      sentence: "The seminar will focus on recent developments in molecular biology and genetics.",
    },
    {
      id: "wfd-20-2",
      type: "write_dictation",
      audioUrl: "",
      sentence: "Governments must balance short-term economic pressures against long-term environmental obligations.",
    },
    {
      id: "wfd-20-3",
      type: "write_dictation",
      audioUrl: "",
      sentence: "The ethical implications of artificial intelligence require careful and ongoing public deliberation.",
    },
  ],
};

export default test20;
