import type { PTETest } from "./types";

export const pteReading7: PTETest = {
  id: "pte-reading-7",
  exam: "PTE",
  title: "PTE Academic Reading — Test 7",
  totalSeconds: 1800,
  tasks: [
    {
      id: 1,
      type: "mc_single",
      taskLabel: "Task 1 of 5 — Multiple Choice, Single Answer",
      instructions: "Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.",
      passage: "Quantum mechanics, the branch of physics governing the behaviour of matter at atomic and subatomic scales, operates according to principles that appear deeply counterintuitive from the perspective of everyday experience. The principle of superposition holds that a quantum particle exists in all possible states simultaneously until it is observed or measured, at which point it 'collapses' into a single definite state. This was famously illustrated by Erwin Schrödinger's 1935 thought experiment, in which a cat sealed in a box with a radioactive atom is simultaneously alive and dead until the box is opened. Quantum entanglement — the phenomenon by which two particles become correlated such that the state of one instantly determines the state of the other regardless of the distance between them — so disturbed Albert Einstein that he described it as 'spooky action at a distance.' These principles, once regarded as philosophical curiosities, now underpin technologies including lasers, MRI machines, and semiconductor devices, and are driving the development of quantum computers that could solve problems intractable for classical computing.",
      stem: "Why did Einstein describe quantum entanglement as 'spooky action at a distance'?",
      options: [
        { label: "A", text: "He believed it violated the principle of superposition." },
        { label: "B", text: "He was troubled by the idea of particles instantly affecting each other across any distance." },
        { label: "C", text: "He thought the experiment was carried out in unscientific conditions." },
        { label: "D", text: "He disagreed with Schrödinger's thought experiment." },
      ],
      correct: "B",
      explanation: "The passage states that entanglement involves 'the state of one instantly determining the state of the other regardless of the distance between them' — the instant action across distance was what disturbed Einstein.",
    },
    {
      id: 2,
      type: "mc_multiple",
      taskLabel: "Task 2 of 5 — Multiple Choice, Multiple Answers",
      instructions: "Read the text and answer the multiple-choice question by selecting all the correct responses. More than one response is correct.",
      passage: "Global food waste represents one of the most significant and underaddressed contributors to climate change. According to the Food and Agriculture Organization of the United Nations, approximately one-third of all food produced globally — some 1.3 billion tonnes annually — is lost or wasted along the supply chain, from farm to consumer. In high-income countries, the majority of waste occurs at the retail and consumer end: overbuying, confusion over date labels, and cosmetic standards that lead supermarkets to reject imperfect produce. In low- and middle-income countries, losses are more concentrated at the production, post-harvest, and processing stages, driven by inadequate storage infrastructure, poor cold chain logistics, and limited processing capacity. The environmental cost is substantial: the water, land, energy, and agricultural inputs embodied in wasted food represent a significant portion of global resource use, and decomposing food in landfill generates methane — a greenhouse gas with a warming potential approximately 25 times that of CO₂ over a 100-year period.",
      stem: "According to the passage, which TWO factors contribute to food waste in high-income countries?",
      options: [
        { label: "A", text: "Poor cold chain logistics" },
        { label: "B", text: "Overbuying by consumers" },
        { label: "C", text: "Inadequate storage infrastructure" },
        { label: "D", text: "Supermarket cosmetic standards rejecting imperfect produce" },
        { label: "E", text: "Insufficient processing capacity" },
      ],
      pickCount: 2,
      correct: ["B", "D"],
      explanation: "The passage lists 'overbuying' (B) and 'cosmetic standards that lead supermarkets to reject imperfect produce' (D) as high-income country waste drivers. A, C, and E are described as low/middle-income country issues.",
    },
    {
      id: 3,
      type: "reorder",
      taskLabel: "Task 3 of 5 — Re-order Paragraphs",
      instructions: "The text below has been placed in a random order. Arrange the sentences in the correct order by clicking them into sequence.",
      sentences: [
        { id: "s1", text: "The development of effective vaccines against infectious disease represents one of public health's greatest achievements, yet the scientific journey from concept to clinical use is rarely straightforward." },
        { id: "s2", text: "Following laboratory development, vaccine candidates must pass through a series of clinical trial phases: Phase I establishes safety in a small group of healthy volunteers; Phase II examines immune response and dosing in a larger group; Phase III tests efficacy and safety in tens of thousands of participants." },
        { id: "s3", text: "The initial stage involves identifying antigens — components of a pathogen that the immune system can learn to recognise and target — and developing a formulation that safely presents these antigens to stimulate an immune response without causing disease." },
        { id: "s4", text: "Regulatory agencies then review all trial data before granting approval, after which post-market surveillance continues to monitor long-term safety in the broader population." },
        { id: "s5", text: "This rigorous multi-stage process typically takes ten to fifteen years and costs hundreds of millions of dollars, though the COVID-19 pandemic demonstrated that timeline compression is possible when global scientific collaboration and resources are mobilised at unprecedented scale." },
      ],
      correctOrder: ["s1", "s3", "s2", "s4", "s5"],
      reorderExplanation: "The sequence is: introduction (s1) → antigen identification and formulation (s3) → clinical trial phases (s2) → regulatory review and surveillance (s4) → summary of timeline and COVID exception (s5).",
    },
    {
      id: 4,
      type: "rfib",
      taskLabel: "Task 4 of 5 — Reading: Fill in the Blanks",
      instructions: "In the text below some words are missing. Drag words from the box to the appropriate place in the text. Not all words will be used.",
      rfibText: "Stars are formed within vast clouds of gas and dust known as {{1}} nebulae, where gravitational forces cause regions of higher density to {{2}} and heat up. When the core temperature reaches approximately 10 million degrees Celsius, nuclear {{3}} begins, fusing hydrogen atoms into helium and releasing enormous quantities of energy as light and heat. The outward pressure of this energy production balances the inward pull of gravity, maintaining the star in a stable state known as the {{4}} sequence. When hydrogen in the core is exhausted, the star expands into a red giant before ultimately {{5}} into a white dwarf, neutron star, or, for the most massive stars, a black hole.",
      wordBank: ["molecular", "collapse", "fusion", "main", "collapsing", "fission", "plasma", "nebular"],
      blanks: [
        { id: 1, correct: "molecular", explanation: "Stars form within 'molecular nebulae' — the standard astronomical term for star-forming gas clouds." },
        { id: 2, correct: "collapse", explanation: "Regions of higher density 'collapse' under gravitational forces, heating the protostar core." },
        { id: 3, correct: "fusion", explanation: "Nuclear 'fusion' — combining hydrogen into helium — is the energy source of stars." },
        { id: 4, correct: "main", explanation: "The stable burning phase is the 'main' sequence — the 'main sequence' is the standard term." },
        { id: 5, correct: "collapsing", explanation: "After the red giant phase the star ends by 'collapsing' into a compact remnant." },
      ],
    },
    {
      id: 5,
      type: "rwfib",
      taskLabel: "Task 5 of 5 — Reading & Writing: Fill in the Blanks",
      instructions: "Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer choice for each blank.",
      rwfibText: "Universal healthcare systems aim to ensure that all {{1}} of a country can access medical services without facing financial {{2}}. Countries with universal systems fund them through a variety of mechanisms, including general taxation, mandatory social insurance {{3}}, or a combination of both. Research consistently shows that universal healthcare systems {{4}} better health outcomes at lower per-capita cost than predominantly private systems, though the evidence is {{5}} by differences in population health behaviours, national wealth, and data quality. The design of benefit packages — which services are {{6}} under the public system — remains a contested political question in all universal systems.",
      rwfibBlanks: [
        { id: 1, options: ["residents", "tourists", "employees", "taxpayers"], correct: "residents", explanation: "'Residents' of a country are the intended beneficiaries of universal healthcare — all people living there." },
        { id: 2, options: ["hardship", "bureaucracy", "delays", "inequality"], correct: "hardship", explanation: "Financial 'hardship' — the economic burden of medical costs — is what universal systems aim to prevent." },
        { id: 3, options: ["contributions", "incentives", "penalties", "grants"], correct: "contributions", explanation: "Social insurance 'contributions' — payments made by workers and employers into a social fund — finance some systems." },
        { id: 4, options: ["achieve", "promise", "attempt", "model"], correct: "achieve", explanation: "Research shows universal systems 'achieve better health outcomes' — actually attain them at lower cost." },
        { id: 5, options: ["complicated", "supported", "contradicted", "confirmed"], correct: "complicated", explanation: "The evidence is 'complicated by differences' in population factors — made harder to interpret cleanly." },
        { id: 6, options: ["covered", "restricted", "promoted", "funded"], correct: "covered", explanation: "Services that are 'covered' under the public system — included in the benefit package and paid for." },
      ],
    },
  ],
};
